version: "3.7"

services:
  test:
    container_name: test
    image: feg_gateway_go_base
    build:
      target: base
      context: ../../../
      dockerfile: feg/gateway/docker/go/Dockerfile
    volumes:
      - ../../../:/magma
      - ../configs:/etc/magma
      - gwcerts:/var/opt/magma/certs
      - gwconfigs:/var/opt/magma/configs
    network_mode: host
    command: tail -f /dev/null

  hss:
    container_name: hss
    image: feg_gateway_go
    volumes:
      - ../configs:/etc/magma
      - gwcerts:/var/opt/magma/certs
      - gwconfigs:/var/opt/magma/configs
    restart: always
    network_mode: host
    command: envdir /var/opt/magma/envdir /var/opt/magma/bin/hss -logtostderr=true -v=0

