# Copyright (c) 2018-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

# Default values for agw.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

release_group: null

## Key Values for docker inside VM
feg:
  image:
    docker_registry: ""
    tag: "latest"
  proxy:
    local_port: 8443
    cloud_address: orc8r-proxy.magma.svc.cluster.local
    cloud_port: 9443
    bootstrap_address: orc8r-bootstrap-legacy.magma.svc.cluster.local
    bootstrap_port: 9444
  repo:
    url: https://github.com/facebookincubator/magma/
    branch: master
## Key Values for VM running using virtlet runtime
image:
  repository: virtlet.cloud/cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

labels:
  node_selector_key: extraRuntime
  node_selector_value: virtlet

pod:
  affinity:
    anti:
      type:
        default: preferredDuringSchedulingIgnoredDuringExecution
      topologyKey:
        default: kubernetes.io/hostname
  replicas:
    server: 1
  resources:
    enabled: true
    server:
      requests:
        memory: "2048Mi"
        cpu: "100m"
      limits:
        memory: "4096Mi"
        cpu: "2000m"

service:
  type: ClusterIP
  ports:
    local:
      port: 8443
      targetport: 8443
      nodePort: ""
    cloud:
      port: 9443
      targetport: 9443
      nodePort: ""
    bootstrap:
      port: 9444
      targetport: 9444
      nodePort: ""
    ssh:
      port: 22
      targetport: 22
      nodePort: ""

nodeSelector:
  extraRuntime: virtlet

tolerations: []

affinity: {}

virtlet:
  vcpuCount: 2
  rootVolumeSize: 20Gi
  diskDriver: virtio
  sshKeys: |
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCaJEcFDXEK2ZbX0ZLS1EIYFZRbDAc
  ssh_pwauth: True
  user:
    users:
    - name: testuser
      gecos: User
      primary-group: testuser
      groups: users
      lock_passwd: false
      shell: /bin/bash
      # the password is "testuser"
      passwd: "$6$rounds=4096$wPs4Hz4tfs$a8ssMnlvH.3GX88yxXKF2cKMlVULsnydoOKgkuStTErTq2dzKZiIx9R/pPWWh5JLxzoZEx7lsSX5T2jW5WISi1"
      sudo: ALL=(ALL) NOPASSWD:ALL

manifests:
  deployment: true
  service: true
  configmap_env: true
  configmap_bin: true
  secrets: true
  rbac: true
