---
swagger: '2.0'
info:
  title: Magmad Model Definitions and Paths
  description: Magma REST APIs
  version: 1.0.0

paths:
  /networks:
    get:
      summary: List all networks
      tags:
      - Networks
      responses:
        '200':
          description: List of network ids
          schema:
            type: array
            items:
              $ref: './swagger-common.yml#/definitions/network_id'
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    post:
      summary: Add a new network
      tags:
      - Networks
      parameters:
      - in: query
        name: requested_id
        type: string
        description: The id of network requested by user
        pattern: '^[a-z_][\da-z_]+$'
        minLength: 1
        maxLength: 100
        required: false
      - in: query
        name: new_workflow_flag
        type: boolean
        description: Set to true to disable config creation
        required: false
      - in: body
        name: network_record
        description: Network object that needs to be added
        required: true
        schema:
          $ref: '#/definitions/network_record'
      responses:
        '201':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'

  /networks/{network_id}:
    get:
      summary: Retrieve Network Configs
      tags:
      - Networks
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      responses:
        '201':
          description: Network Configs
          schema:
            $ref: '#/definitions/network_record'
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    put:
      summary: Set Network Configs
      tags:
      - Networks
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - in: body
        name: network_record
        description: Network Configs
        required: true
        schema:
          $ref: '#/definitions/network_record'
      responses:
        '200':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    delete:
      summary: Delete a network
      tags:
      - Networks
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      responses:
        '204':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'

  /networks/{network_id}/gateways:
    get:
      summary: List gateways in the network
      tags:
      - Gateways
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      responses:
        '200':
          description: List of gateway ids
          schema:
            type: array
            items:
              $ref: './swagger-common.yml#/definitions/gateway_id'
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    post:
      summary: Add a new gateway to the network
      tags:
      - Gateways
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - in: query
        type: string
        name: requested_id
        description: The id of gateway requested by user
        pattern: '^[a-zA-Z_][\da-zA-Z_-]+$'
        minLength: 1
        maxLength: 100
        required: false
      - in: query
        name: new_workflow_flag
        type: boolean
        description: Set to true to disable config creation
        required: false
      - in: body
        name: Gateway Record
        description: Gateway Record Of the Gateway to Add
        required: true
        schema:
          $ref: '#/definitions/access_gateway_record'
      responses:
        '201':
          description: New Logical ID of the Registered Gateway
          schema:
            $ref: './swagger-common.yml#/definitions/gateway_id'
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'

  /networks/{network_id}/gateways?view=full:
    get:
      summary: Get full view of all gateways in a network
      tags:
        - Gateways
      parameters:
        - $ref: './swagger-common.yml#/parameters/network_id'
        - in: query
          name: gateway_ids
          type: array
          required: false
          items:
            type: string
      responses:
        '200':
          description: Materialized views of gateways specified in query
          schema:
            type: array
            items:
              $ref: '#/definitions/gateway_state'
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'

  /networks/{network_id}/gateways/{gateway_id}:
    get:
      summary: Get Registered Gateway's Record
      tags:
      - Gateways
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - $ref: './swagger-common.yml#/parameters/gateway_id'
      responses:
        '200':
          description: Gateway Record on Success
          schema:
            $ref: '#/definitions/access_gateway_record'
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    put:
      summary: Modify Gateway Record
      tags:
      - Gateways
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - $ref: './swagger-common.yml#/parameters/gateway_id'
      - in: body
        name: MutableGatewayRecord
        description: Gateway Configs
        required: true
        schema:
          $ref: '#/definitions/mutable_gateway_record'
      responses:
        '200':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    delete:
      summary: Unregister a gateway from the network
      tags:
      - Gateways
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - $ref: './swagger-common.yml#/parameters/gateway_id'
      responses:
        '204':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'

  /networks/{network_id}/gateways/{gateway_id}/configs:
    post:
      summary: Create Gateway Configs
      tags:
      - Gateways
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - $ref: './swagger-common.yml#/parameters/gateway_id'
      - in: body
        name: GatewayConfigs
        description: Gateway Configs
        required: true
        schema:
          $ref: '#/definitions/magmad_gateway_config'
      responses:
        '201':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    get:
      summary: Retrieve Gateway Configs
      tags:
      - Gateways
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - $ref: './swagger-common.yml#/parameters/gateway_id'
      responses:
        '200':
          description: Retreive Gateway Configs
          schema:
            $ref: '#/definitions/magmad_gateway_config'
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    put:
      summary: Modify Gateway Configs
      tags:
      - Gateways
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - $ref: './swagger-common.yml#/parameters/gateway_id'
      - in: body
        name: GatewayConfigs
        description: Gateway Configs
        required: true
        schema:
          $ref: '#/definitions/magmad_gateway_config'
      responses:
        '200':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    delete:
      summary: Delete Gateway Configs
      tags:
      - Gateways
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - $ref: './swagger-common.yml#/parameters/gateway_id'
      responses:
        '204':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'

  /networks/{network_id}/gateways/{gateway_id}/command/reboot:
    post:
      summary: Reboot gateway device
      tags:
      - Commands
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - $ref: './swagger-common.yml#/parameters/gateway_id'
      responses:
        '200':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'

  /networks/{network_id}/gateways/{gateway_id}/command/restart_services:
    post:
      summary: Restart gateway services
      tags:
      - Commands
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - $ref: './swagger-common.yml#/parameters/gateway_id'
      - in: body
        name: Services
        description: Services
        required: true
        schema:
          type: array
          items:
            type: string
          example: []
      responses:
        '200':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'

  /networks/{network_id}/gateways/{gateway_id}/command/ping:
    post:
      summary: Ping host(s) from gateway
      tags:
      - Commands
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - $ref: './swagger-common.yml#/parameters/gateway_id'
      - in: body
        name: Ping request
        description: Ping request
        required: true
        schema:
          $ref: '#/definitions/ping_request'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/ping_response'
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'


  /networks/{network_id}/gateways/{gateway_id}/command/generic:
    post:
      summary: Execute generic command on gateway
      tags:
      - Commands
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - $ref: './swagger-common.yml#/parameters/gateway_id'
      - in: body
        name: Parameters
        description: Parameters
        required: true
        schema:
          $ref: '#/definitions/generic_command_params'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/generic_command_response'
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'

definitions:
  network_record:
    type: object
    required:
    - name
    properties:
      name:
        type: string
        minLength: 1
        example: SampleNetwork
        x-nullable: false
  hw_gateway_id:
    type: object
    required:
    - id
    properties:
      id:
        type: string
        minLength: 1
        x-nullable: false
        x-go-custom-tag: 'magma_alt_name:"Id"'
        example: 22ffea10-7fc4-4427-975a-b9e4ce8f6f4d
  challenge_key:
    type: object
    required:
    - key_type
    properties:
      key_type:
        type: string
        enum:
        - ECHO
        - SOFTWARE_ECDSA_SHA256
        example: SOFTWARE_ECDSA_SHA256
        x-nullable: false
      key:
        type: string
        format: byte
        x-nullable: true
        example: MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAE+Lckvw/eeV8CemEOWpX30/5XhTHKx/mm6T9MpQWuIM8sOKforNm5UPbZrdOTPEBAtGwJB6Uk9crjCIveFe+sN0zw705L94Giza4ny/6ASBcctCm2JJxFccVsocJIraSC
  mutable_gateway_record:
    type: object
    required:
    - key
    properties:
      name:
        type: string
        minLength: 1
        example: SoDoSoPa Tower
      key:
        $ref: '#/definitions/challenge_key'
  access_gateway_record:
    type: object
    required:
    - hw_id
    - key
    properties:
      hw_id:
        $ref: '#/definitions/hw_gateway_id'
        x-go-custom-tag: 'magma_alt_name:"HwId"'
      name:
        type: string
        minLength: 1
        example: South Park's CtPa Town Tower
      key:
        $ref: '#/definitions/challenge_key'
  magmad_gateway_config:
    type: object
    properties:
      checkin_interval:
        type: integer
        format: int32
        example: 60
      checkin_timeout:
        type: integer
        format: int32
        example: 10
      autoupgrade_enabled:
        type: boolean
        example: true
      autoupgrade_poll_interval:
        type: integer
        format: int32
        example: 300
      tier:
        type: string
        minLength: 1
        description: ID of tier within network that gateway is grouped into
        example: 'default'
      dynamic_services:
        type: array
        items:
          type: string
        example: []
      feature_flags:
        type: object
        additionalProperties:
          type: boolean
        example:
          newfeature1: true
          newfeature2: false
  ping_request:
    type: object
    required:
    - hosts
    properties:
      packets:
        type: integer
        format: int32
        minimum: 1
        default: 4
        example: 4
      hosts:
        type: array
        items:
          type: string
        example: ["example.com"]
  ping_result:
    type: object
    required:
    - host_or_ip
    - num_packets
    properties:
      host_or_ip:
        type: string
        minLength: 1
        example: example.com
      num_packets:
        type: integer
        format: int32
        example: 4
      packets_transmitted:
        type: integer
        format: int32
        example: 4
      packets_received:
        type: integer
        format: int32
        example: 4
      avg_response_ms:
        type: number
        format: float
        example: 35.69900131225586
      error:
        type: string
        example: 'error'
  ping_response:
    type: object
    required:
    - pings
    properties:
      pings:
        type: array
        items:
          $ref: '#/definitions/ping_result'
  generic_command_params:
    type: object
    required:
      - command
    properties:
      command:
        type: string
        minLength: 1
        example: command_name
      params:
        type: object
        additionalProperties:
          type: object
        example: {}
  generic_command_response:
    type: object
    properties:
      response:
        type: object
        additionalProperties:
          type: object
        example: {}

  # Full view
  gateway_state:
    type: object
    required:
      - gateway_id
    properties:
      gateway_id:
        $ref: './swagger-common.yml#/definitions/gateway_id'
      config:
        type: object
        additionalProperties:
          type: object
      status:
        $ref: '#/definitions/gateway_status'
      record:
        $ref: '#/definitions/access_gateway_record'
  system_status:
    type: object
    properties:
      time:
        type: integer
        format: uint64
        example: 1234567000
      cpu_user:
        type: integer
        format: uint64
        x-go-custom-tag: 'magma_alt_name:"CpuUser"'
      cpu_system:
        type: integer
        format: uint64
        x-go-custom-tag: 'magma_alt_name:"CpuSystem"'
      cpu_idle:
        type: integer
        format: uint64
        x-go-custom-tag: 'magma_alt_name:"CpuIdle"'
      mem_total:
        type: integer
        format: uint64
      mem_available:
        type: integer
        format: uint64
      mem_used:
        type: integer
        format: uint64
      mem_free:
        type: integer
        format: uint64
      uptime_secs:
        type: integer
        format: uint64
        example: 12345
  gateway_status:
    type: object
    properties:
      checkin_time:
        type: integer
        format: uint64
        example: 1234567890
      hardware_id:
        type: string
      version:
        type: string
      system_status:
        $ref: '#/definitions/system_status'
      cert_expiration_time:
        type: integer
        format: int64
        example: 1234567890
      meta:
        type: object
        additionalProperties:
          type: string
      vpn_ip:
        type: string
        example: 10.0.0.1
      kernel_version:
        type: string
        example: 4.9.0-6-amd64
      kernel_versions_installed:
        type: array
        x-omitempty: true
        items:
          type: string
        example: ["4.9.0-6-amd64", "4.9.0-7-amd64"]
