---
- name: Set hostname in /etc/hosts
  shell: echo "127.0.0.1 {{ansible_hostname}}" | sudo tee -a /etc/hosts > /dev/null

- name: Force new snowflake ID
  shell: snowflake -m --force-new-key
  become: true

- name: Create cert and config directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  become: true
  with_items:
    - "{{ agwCertsPath }}"
    - "{{ agwConfigPath }}"

- name: Copy keys to certificate directory
  become: true
  copy:
    src: "{{ dirSecretsLocal }}/rootCA.pem"
    dest: "{{ agwCertsPath }}/rootCA.pem"

- name: Copy control_proxy
  become: true
  template:
    src: roles/agw-platform/files/control_proxy.j2
    dest: "{{ agwConfigPath }}/control_proxy.yml"

- name: Read magmad yaml file
  command: cat /etc/magma/magmad.yml
  register: magmad_raw_config





- name: Copy subscriber sim to the gateways
  become: true
  ansible.builtin.copy:
    src: /root/magma/lte/gateway/python/scripts/metrics_load_sim.py
    dest: /usr/bin/metrics_load_sim
    owner: root
    group: root
    mode: 0744

- name: create systemd service unit
  become: true
  template:
    src: subscriber_metrics_sim.j2
    dest: /etc/systemd/system/subscriber_metrics_sim.service
    owner: "root"
    group: "root"
    mode: 0644

- name: reenable subscriber simulator service
  become: true
  command: systemctl reenable subscriber_metrics_sim.service

- name: restart subscriber simulator service
  become: true
  service:
    name: subscriber_metrics_sim
    state: restarted

- name: ensure subscriber simulator service is enabled and started
  service:
    name: subscriber_metrics_sim
    state: started
    enabled: yes

- name: Add subscriber simulator as metric scrape targets
  set_fact:
      magmad_new_config: "{{ magmad_config | combine ({'metricsd': metrics_config})}}"
  vars:
    magmad_config: "{{ magmad_raw_config.stdout | from_yaml }}"
    metrics_config: "{{ magmad_config['metricsd'] | combine({'metric_scrape_targets': metric_scrape_targets})}}"
    metric_scrape_targets: [

      {
        'url' : "http://0.0.0.0:{{ subscriber_metrics_sim_port }}/metrics",
        'name': 'subscriber_simulator',
        'interval': 60
      }
    ]

- name: Debug magmad config
  debug:
    var: magmad_new_config

- name: Rewriting magmad config with metric scrape configs
  become: true
  copy:
    dest: "/etc/magma/magmad.yml"
    content: "{{magmad_new_config | to_yaml}}"

- name: Restart magma services
  become: true
  systemd:
    state: restarted
    name: "{{ item }}"
    no_block: true
  with_items:
    - "{{ servicesMagma }}"