---
- name: Set hostname in /etc/hosts
  shell: echo "127.0.0.1 {{ansible_hostname}}" | sudo tee -a /etc/hosts > /dev/null

- name: Force new snowflake ID
  shell: snowflake -m --force-new-key
  become: true
  tags: reset_hardware_id

- name: Dump hardware id
  shell: cat /etc/snowflake
  register: hardware_id

- name: Create cert and config directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  become: true
  with_items:
    - "{{ agwCertsPath }}"
    - "{{ agwConfigPath }}"

- name: Copy keys to certificate directory
  become: true
  copy:
    src: "{{ dirSecretsLocal }}/rootCA.pem"
    dest: "{{ agwCertsPath }}/rootCA.pem"

- name: Copy control_proxy
  become: true
  template:
    src: roles/agw-platform/files/control_proxy.j2
    dest: "{{ agwConfigPath }}/control_proxy.yml"

- name: Restart magma services
  become: true
  systemd:
    state: restarted
    name: "{{ item }}"
    no_block: true
  with_items:
    - "{{ servicesMagma }}"

- name: load var from file
  delegate_to: localhost
  ignore_errors: true
  include_vars:
    file: "{{dirLocalInventory}}/gw_hwid.json"
    name: gw_hwid_map

- name: append more key/values
  delegate_to: localhost
  set_fact:
    gw_hwid_map: "{{ gw_hwid_map | default([]) | combine({ansible_default_ipv4.address: hardware_id.stdout }) }}"

- name: write var to file
  delegate_to: localhost
  copy: 
    content: "{{ gw_hwid_map | to_nice_json }}" 
    dest: "{{dirLocalInventory}}/gw_hwid.json"    