---
- include: provision-gateway-instance.yaml
  tags: clusterGateway
- include: provision-test-instances.yaml
  tags: clusterStart
- include: configure-test-instances.yaml
  tags: clusterConfigure
- include: cleanup-test-instances.yaml
  tags: clusterCleanup
