# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

version: "3.7"

services:
  controller:
    image: "${DOCKER_REGISTRY}/controller:${IMAGE_VERSION}"
    volumes:
      - /var/opt/magma/certs:/var/opt/magma/certs
      - /var/opt/magma/configs:/var/opt/magma/configs
      - /var/opt/magma/envdir:/var/opt/magma/envdir
    ports:
      - "8080:8080"
      - "9079-9108:9079-9112"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"