#Installing Ansible Server
#Needs to be run as sudo user (instead of becoming sudo user for each play)


- name: installing ansible dependent packages
  apt: 
    name: "{{ bootPackages }}" 
    state: present
    update_cache: yes
  with_items:
    - software-properties-common
    - python3-boto
    - python3-boto3
    - python3-botocore
    - ansible

