// Code generated by go-swagger; DO NOT EDIT.

package wifi_gateways

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"magma/orc8r/cloud/go/obsidian/swagger/v1/models"
)

// NewPutWifiNetworkIDGatewaysGatewayIDDescriptionParams creates a new PutWifiNetworkIDGatewaysGatewayIDDescriptionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutWifiNetworkIDGatewaysGatewayIDDescriptionParams() *PutWifiNetworkIDGatewaysGatewayIDDescriptionParams {
	return &PutWifiNetworkIDGatewaysGatewayIDDescriptionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutWifiNetworkIDGatewaysGatewayIDDescriptionParamsWithTimeout creates a new PutWifiNetworkIDGatewaysGatewayIDDescriptionParams object
// with the ability to set a timeout on a request.
func NewPutWifiNetworkIDGatewaysGatewayIDDescriptionParamsWithTimeout(timeout time.Duration) *PutWifiNetworkIDGatewaysGatewayIDDescriptionParams {
	return &PutWifiNetworkIDGatewaysGatewayIDDescriptionParams{
		timeout: timeout,
	}
}

// NewPutWifiNetworkIDGatewaysGatewayIDDescriptionParamsWithContext creates a new PutWifiNetworkIDGatewaysGatewayIDDescriptionParams object
// with the ability to set a context for a request.
func NewPutWifiNetworkIDGatewaysGatewayIDDescriptionParamsWithContext(ctx context.Context) *PutWifiNetworkIDGatewaysGatewayIDDescriptionParams {
	return &PutWifiNetworkIDGatewaysGatewayIDDescriptionParams{
		Context: ctx,
	}
}

// NewPutWifiNetworkIDGatewaysGatewayIDDescriptionParamsWithHTTPClient creates a new PutWifiNetworkIDGatewaysGatewayIDDescriptionParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutWifiNetworkIDGatewaysGatewayIDDescriptionParamsWithHTTPClient(client *http.Client) *PutWifiNetworkIDGatewaysGatewayIDDescriptionParams {
	return &PutWifiNetworkIDGatewaysGatewayIDDescriptionParams{
		HTTPClient: client,
	}
}

/* PutWifiNetworkIDGatewaysGatewayIDDescriptionParams contains all the parameters to send to the API endpoint
   for the put wifi network ID gateways gateway ID description operation.

   Typically these are written to a http.Request.
*/
type PutWifiNetworkIDGatewaysGatewayIDDescriptionParams struct {

	// Description.
	Description models.GatewayDescription

	/* GatewayID.

	   Gateway ID
	*/
	GatewayID string

	/* NetworkID.

	   Network ID
	*/
	NetworkID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put wifi network ID gateways gateway ID description params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutWifiNetworkIDGatewaysGatewayIDDescriptionParams) WithDefaults() *PutWifiNetworkIDGatewaysGatewayIDDescriptionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put wifi network ID gateways gateway ID description params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutWifiNetworkIDGatewaysGatewayIDDescriptionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put wifi network ID gateways gateway ID description params
func (o *PutWifiNetworkIDGatewaysGatewayIDDescriptionParams) WithTimeout(timeout time.Duration) *PutWifiNetworkIDGatewaysGatewayIDDescriptionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put wifi network ID gateways gateway ID description params
func (o *PutWifiNetworkIDGatewaysGatewayIDDescriptionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put wifi network ID gateways gateway ID description params
func (o *PutWifiNetworkIDGatewaysGatewayIDDescriptionParams) WithContext(ctx context.Context) *PutWifiNetworkIDGatewaysGatewayIDDescriptionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put wifi network ID gateways gateway ID description params
func (o *PutWifiNetworkIDGatewaysGatewayIDDescriptionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put wifi network ID gateways gateway ID description params
func (o *PutWifiNetworkIDGatewaysGatewayIDDescriptionParams) WithHTTPClient(client *http.Client) *PutWifiNetworkIDGatewaysGatewayIDDescriptionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put wifi network ID gateways gateway ID description params
func (o *PutWifiNetworkIDGatewaysGatewayIDDescriptionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDescription adds the description to the put wifi network ID gateways gateway ID description params
func (o *PutWifiNetworkIDGatewaysGatewayIDDescriptionParams) WithDescription(description models.GatewayDescription) *PutWifiNetworkIDGatewaysGatewayIDDescriptionParams {
	o.SetDescription(description)
	return o
}

// SetDescription adds the description to the put wifi network ID gateways gateway ID description params
func (o *PutWifiNetworkIDGatewaysGatewayIDDescriptionParams) SetDescription(description models.GatewayDescription) {
	o.Description = description
}

// WithGatewayID adds the gatewayID to the put wifi network ID gateways gateway ID description params
func (o *PutWifiNetworkIDGatewaysGatewayIDDescriptionParams) WithGatewayID(gatewayID string) *PutWifiNetworkIDGatewaysGatewayIDDescriptionParams {
	o.SetGatewayID(gatewayID)
	return o
}

// SetGatewayID adds the gatewayId to the put wifi network ID gateways gateway ID description params
func (o *PutWifiNetworkIDGatewaysGatewayIDDescriptionParams) SetGatewayID(gatewayID string) {
	o.GatewayID = gatewayID
}

// WithNetworkID adds the networkID to the put wifi network ID gateways gateway ID description params
func (o *PutWifiNetworkIDGatewaysGatewayIDDescriptionParams) WithNetworkID(networkID string) *PutWifiNetworkIDGatewaysGatewayIDDescriptionParams {
	o.SetNetworkID(networkID)
	return o
}

// SetNetworkID adds the networkId to the put wifi network ID gateways gateway ID description params
func (o *PutWifiNetworkIDGatewaysGatewayIDDescriptionParams) SetNetworkID(networkID string) {
	o.NetworkID = networkID
}

// WriteToRequest writes these params to a swagger request
func (o *PutWifiNetworkIDGatewaysGatewayIDDescriptionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Description); err != nil {
		return err
	}

	// path param gateway_id
	if err := r.SetPathParam("gateway_id", o.GatewayID); err != nil {
		return err
	}

	// path param network_id
	if err := r.SetPathParam("network_id", o.NetworkID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
