// Code generated by go-swagger; DO NOT EDIT.

package wifi_gateways

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"magma/orc8r/cloud/go/obsidian/swagger/v1/models"
)

// NewPutWifiNetworkIDGatewaysGatewayIDWifiParams creates a new PutWifiNetworkIDGatewaysGatewayIDWifiParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutWifiNetworkIDGatewaysGatewayIDWifiParams() *PutWifiNetworkIDGatewaysGatewayIDWifiParams {
	return &PutWifiNetworkIDGatewaysGatewayIDWifiParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutWifiNetworkIDGatewaysGatewayIDWifiParamsWithTimeout creates a new PutWifiNetworkIDGatewaysGatewayIDWifiParams object
// with the ability to set a timeout on a request.
func NewPutWifiNetworkIDGatewaysGatewayIDWifiParamsWithTimeout(timeout time.Duration) *PutWifiNetworkIDGatewaysGatewayIDWifiParams {
	return &PutWifiNetworkIDGatewaysGatewayIDWifiParams{
		timeout: timeout,
	}
}

// NewPutWifiNetworkIDGatewaysGatewayIDWifiParamsWithContext creates a new PutWifiNetworkIDGatewaysGatewayIDWifiParams object
// with the ability to set a context for a request.
func NewPutWifiNetworkIDGatewaysGatewayIDWifiParamsWithContext(ctx context.Context) *PutWifiNetworkIDGatewaysGatewayIDWifiParams {
	return &PutWifiNetworkIDGatewaysGatewayIDWifiParams{
		Context: ctx,
	}
}

// NewPutWifiNetworkIDGatewaysGatewayIDWifiParamsWithHTTPClient creates a new PutWifiNetworkIDGatewaysGatewayIDWifiParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutWifiNetworkIDGatewaysGatewayIDWifiParamsWithHTTPClient(client *http.Client) *PutWifiNetworkIDGatewaysGatewayIDWifiParams {
	return &PutWifiNetworkIDGatewaysGatewayIDWifiParams{
		HTTPClient: client,
	}
}

/* PutWifiNetworkIDGatewaysGatewayIDWifiParams contains all the parameters to send to the API endpoint
   for the put wifi network ID gateways gateway ID wifi operation.

   Typically these are written to a http.Request.
*/
type PutWifiNetworkIDGatewaysGatewayIDWifiParams struct {

	/* Config.

	   New wifi configuration
	*/
	Config *models.GatewayWifiConfigs

	/* GatewayID.

	   Gateway ID
	*/
	GatewayID string

	/* NetworkID.

	   Network ID
	*/
	NetworkID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put wifi network ID gateways gateway ID wifi params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutWifiNetworkIDGatewaysGatewayIDWifiParams) WithDefaults() *PutWifiNetworkIDGatewaysGatewayIDWifiParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put wifi network ID gateways gateway ID wifi params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutWifiNetworkIDGatewaysGatewayIDWifiParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put wifi network ID gateways gateway ID wifi params
func (o *PutWifiNetworkIDGatewaysGatewayIDWifiParams) WithTimeout(timeout time.Duration) *PutWifiNetworkIDGatewaysGatewayIDWifiParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put wifi network ID gateways gateway ID wifi params
func (o *PutWifiNetworkIDGatewaysGatewayIDWifiParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put wifi network ID gateways gateway ID wifi params
func (o *PutWifiNetworkIDGatewaysGatewayIDWifiParams) WithContext(ctx context.Context) *PutWifiNetworkIDGatewaysGatewayIDWifiParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put wifi network ID gateways gateway ID wifi params
func (o *PutWifiNetworkIDGatewaysGatewayIDWifiParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put wifi network ID gateways gateway ID wifi params
func (o *PutWifiNetworkIDGatewaysGatewayIDWifiParams) WithHTTPClient(client *http.Client) *PutWifiNetworkIDGatewaysGatewayIDWifiParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put wifi network ID gateways gateway ID wifi params
func (o *PutWifiNetworkIDGatewaysGatewayIDWifiParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithConfig adds the config to the put wifi network ID gateways gateway ID wifi params
func (o *PutWifiNetworkIDGatewaysGatewayIDWifiParams) WithConfig(config *models.GatewayWifiConfigs) *PutWifiNetworkIDGatewaysGatewayIDWifiParams {
	o.SetConfig(config)
	return o
}

// SetConfig adds the config to the put wifi network ID gateways gateway ID wifi params
func (o *PutWifiNetworkIDGatewaysGatewayIDWifiParams) SetConfig(config *models.GatewayWifiConfigs) {
	o.Config = config
}

// WithGatewayID adds the gatewayID to the put wifi network ID gateways gateway ID wifi params
func (o *PutWifiNetworkIDGatewaysGatewayIDWifiParams) WithGatewayID(gatewayID string) *PutWifiNetworkIDGatewaysGatewayIDWifiParams {
	o.SetGatewayID(gatewayID)
	return o
}

// SetGatewayID adds the gatewayId to the put wifi network ID gateways gateway ID wifi params
func (o *PutWifiNetworkIDGatewaysGatewayIDWifiParams) SetGatewayID(gatewayID string) {
	o.GatewayID = gatewayID
}

// WithNetworkID adds the networkID to the put wifi network ID gateways gateway ID wifi params
func (o *PutWifiNetworkIDGatewaysGatewayIDWifiParams) WithNetworkID(networkID string) *PutWifiNetworkIDGatewaysGatewayIDWifiParams {
	o.SetNetworkID(networkID)
	return o
}

// SetNetworkID adds the networkId to the put wifi network ID gateways gateway ID wifi params
func (o *PutWifiNetworkIDGatewaysGatewayIDWifiParams) SetNetworkID(networkID string) {
	o.NetworkID = networkID
}

// WriteToRequest writes these params to a swagger request
func (o *PutWifiNetworkIDGatewaysGatewayIDWifiParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Config != nil {
		if err := r.SetBodyParam(o.Config); err != nil {
			return err
		}
	}

	// path param gateway_id
	if err := r.SetPathParam("gateway_id", o.GatewayID); err != nil {
		return err
	}

	// path param network_id
	if err := r.SetPathParam("network_id", o.NetworkID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
