---
swagger: '2.0'

info:
  title: Magma
  description: Magma REST APIs
  version: 1.0.0

basePath: /magma/v1

consumes:
  - application/json

produces:
  - application/json

schemes:
  - https
  - http

tags:
  - name: Networks
    description: Everything about networks
  - name: Gateways
    description: Provision and manage gateways

paths:
  /foo:
    get:
      summary: Mock API path so the YAML passes spec
      responses:
        '200':
          description: Bar baz
          schema:
            type: integer

responses:
  UnexpectedError:
    description: Unexpected Error
    schema:
      $ref: '#/definitions/error'

parameters:
  # network ID parameter in query string (for POST requests)
  network_id_query:
    in: query
    name: network_id
    type: string
    description: Network ID
    pattern: '^[a-z_][\da-z_]+$'
    minLength: 1
    maxLength: 100
    required: true
  network_id:
    in: path
    name: network_id
    description: Network ID
    required: true
    type: string
  gateway_id:
    in: path
    name: gateway_id
    description: Gateway ID
    required: true
    type: string

definitions:
  network_id:
    type: string
    minLength: 1
    x-nullable: false
    example: network_1
    pattern: '^[a-z][\da-z_]+$'
  network_name:
    type: string
    minLength: 1
    x-nullable: false
    example: Sample Network
  network_description:
    type: strin
    minLength: 1
    x-nullable: false
    example: Foobar network
  gateway_id:
    type: string
    minLength: 1
    example: gw1
  error:
    type: object
    required:
      - message
    properties:
      message:
        type: string
        example: Error string

