- name: check if required infra variables are set
  ansible.builtin.command: "orcl configure check -c infra"
  register: result
  failed_when: result.rc != 0
  tags:
    - install_precheck
    - upgrade_precheck

- name: Open configuration file
  shell: "cat {{config_dir}}/infra.tfvars.json"
  register: result
  tags:
    - install_precheck
    - upgrade_precheck

- name: Set Infra Configs
  set_fact:
    infra_configs: "{{ result.stdout | from_json }}"
  tags:
    - install_precheck
    - upgrade_precheck

