---
# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

# This config override will be moved to /feg/gateway/configs once Docker
# officially replaces the vagrant/systemd workflow. For now, this config
# will override the existing one at feg/gateway/configs.

log_level: INFO
# List of services for magmad to control
magma_services:
  - control_proxy
  - metricsd
  - redis
  - session_proxy
  - s6a_proxy
  - csfb
  - feg_hello
  - health
  - swx_proxy
  - eap_aka
  - eap_router

# List of services that don't provide service303 interface
non_service303_services:
  - control_proxy
  - redis

# Init system to use to control services
# Supported systems include: [systemd, runit, docker]
init_system: docker

# bootstrap_manager config
bootstrap_config:
  # location of the challenge key
  challenge_key: /var/opt/magma/certs/gw_challenge.key

# Flags indicating the magmad features to be enabled
enable_config_streamer: True
enable_upgrade_manager: False
enable_network_monitor: False
enable_systemd_tailer: False
enable_sync_rpc: True

systemd_tailer_poll_interval: 30 # seconds

upgrader_factory:
  module: magma.magmad.upgrade.feg_upgrader
  class: FegUpgraderFactory
  http_base_url: https://api.magma.test/s3/feg

mconfig_modules:
  - orc8r.protos.mconfig.mconfigs_pb2
  - lte.protos.mconfig.mconfigs_pb2
  - feg.protos.mconfig.mconfigs_pb2
