---

promo_user: "{{ ansible_user }}"
promo_group: "{{ ansible_user }}"

prometheus_version: 2.5.0

prometheus_go_version: 1.6.2

prometheus_platform_suffix: "linux-amd64"

prometheus_install_path: /opt/prometheus
prometheus_subdir: "{{ prometheus_install_path }}/prometheus-{{ prometheus_version }}.{{ prometheus_platform_suffix }}"
prometheus_config_path: /etc/prometheus
prometheus_db_path: /data/prometheus/data
prometheus_download_path: /tmp

prometheus_cache_binary_dir: /opt/prometheus
prometheus_cache_queue_capacity: 5

prometheus_port: 9090
prometheus_cache_port: 9091

magma_metrics_endpoint: "{{ lookup('env', 'MAGMA_METRICS_ENDPOINT') }}"
