---

promo_user: "{{ ansible_user }}"
promo_group: "{{ ansible_user }}"

prometheus_version: 2.9.1

prometheus_go_version: 1.6.2

prometheus_platform_suffix: "linux-amd64"

prometheus_install_path: /opt/prometheus
prometheus_subdir: "{{ prometheus_install_path }}/prometheus-{{ prometheus_version }}.{{ prometheus_platform_suffix }}"
prometheus_config_path: /etc/prometheus
prometheus_db_path: /data/prometheus/data
prometheus_download_path: /tmp

pushgateway_version: 0.7.0
pushgateway_install_path: /opt/prometheus/pushgateway
pushgateway_subdir: "{{ pushgateway_install_path }}/pushgateway-{{ pushgateway_version }}.{{ prometheus_platform_suffix }}"

prometheus_port: 9090
pushgateway_port: 9091

magma_metrics_endpoint: "{{ lookup('env', 'MAGMA_METRICS_ENDPOINT') }}"

