---
# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

- name: Create archives directory
  file: path=/var/opt/magma/archives state=directory
  when: preburn

- name: Copy magma service unit file
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - {src: 'magma.service', dest: '/etc/systemd/system/magma@.service'}
    - {src: 'magma_certifier.service', dest: '/etc/systemd/system/magma@certifier.service'}
    - {src: 'magma_bootstrapper.service', dest: '/etc/systemd/system/magma@bootstrapper.service'}
    - {src: 'magma_obsidian.service', dest: '/etc/systemd/system/magma@obsidian.service'}
    - {src: 'magma_metricsd.service', dest: '/etc/systemd/system/magma@metricsd.service'}
  when: full_provision

- name: Stop running magma services
  when: full_provision and restart_controller
  systemd: name=magma@* state=stopped daemon_reload=yes
  ignore_errors: yes

- name: Restart the magma services
  when: full_provision and restart_controller
  systemd: name=magma@{{ item.key }} state=restarted daemon_reload=yes enabled=yes
  with_items: "{{ service_registry | dict2items }}"

- name: Copy system config files
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - {src: 'rsyslog', dest: '/etc/logrotate.d/rsyslog'}
  when: full_provision
