---
################################################################################
# Copyright (c) Facebook, Inc. and its affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
################################################################################

- name: Set up Magma dev build environment on a local machine
  hosts: dev
  become: yes

  vars:
    magma_root: /home/{{ ansible_user }}/magma
    preburn: false
    full_provision: true

  roles:
    - role: stretch_snapshot
    - role: gateway_dev
      vars:
        distribution: "stretch"
        repo: "dev"
        config_dir: "lte/gateway/configs"
    - role: python_dev
    - role: dev_common
      vars:
        c_build: /home/{{ ansible_user }}/build/c/
        oai_build: "{{ c_build }}/oai"
    - role: magma
      vars:
        c_build: /home/{{ ansible_user }}/build/c/
        oai_build: "{{ c_build }}/oai"
        magma_repo: /home/{{ ansible_user }}/magma-packages
    - role: fluent_bit
