version: "3.7"

services:
  datastore:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: magma_dev
      POSTGRES_PASSWORD: magma_dev
      POSTGRES_DB: magma_dev
    volumes:
      - $PWD/../../../.cache/orc8r/pgdata:/var/lib/postgresql/data

  proxy:
    volumes:
      - $PWD/../../../.cache/test_certs:/var/opt/magma/certs
    ports:
      - 9443:9443/tcp  # API/controller port
      - 9444:9444/tcp  # Bootstrapper port
    restart: always

  controller:
    volumes:
      - $PWD/../../../.cache/test_certs:/var/opt/magma/certs
    restart: always