version: "3.7"

services:
  proxy:
    build:
      # Use the temporary context created by the build.py script
      context: /tmp/magma_orc8r_build
      dockerfile: $PWD/proxy/Dockerfile

  controller:
    build:
      # Use the temporary context created by the build.py script
      context: /tmp/magma_orc8r_build
      dockerfile: $PWD/controller/Dockerfile

  test:
    # Test service to spin up a dev container for running unit tests,
    # precommit tests (go fmt), and code gen tools (swagger, protobuf).
    build:
      context: /tmp/magma_orc8r_build
      dockerfile: $PWD/controller/Dockerfile
      target: base
    entrypoint: /bin/bash -lc
    command: ['echo Hello World!']