version: "3.7"

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432/tcp
    volumes:
      - $PWD/../../../.cache/orc8r/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: magma_dev
      POSTGRES_PASSWORD: magma_dev
      POSTGRES_DB: magma_dev
    restart: always

  maria:
    image: mariadb:10.2
    volumes:
      - $PWD/../../../.cache/orc8r/mariadata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: magma
      MYSQL_DATABASE: magma_dev
      MYSQL_USER: magma_dev
      MYSQL_PASSWORD: magma_dev
      SQL_MODE: ANSI_QUOTES
    command: mysqld --sql_mode="ANSI_QUOTES"
    restart: always

  proxy:
    ports:
      - 9443:9443/tcp  # API/controller port
      - 9444:9444/tcp  # Bootstrapper port
    volumes:
      - $PWD/../../../.cache/test_certs:/var/opt/magma/certs
    environment:
      CONTROLLER_HOSTNAME: controller.magma.test
      PROXY_BACKENDS: controller  # Uses Docker internal DNS for controller
      # HTTP_PROXY_HOSTNAME: proxy.magma.test
      # HTTP_PROXY_BACKEND: www.magma.test
      HTTP_PROXY_DOCKER_HOSTNAME: docker.io
      HTTP_PROXY_GITHUB_HOSTNAME: github.com
      TEST_MODE: "1"  # Used to run dev scripts on startup
    restart: always

  controller:
    volumes:
      - $PWD/../../../.cache/test_certs:/var/opt/magma/certs
    environment:
      TEST_MODE: "1"  # Used to run dev scripts on startup
      SQL_DRIVER: postgres
      DATABASE_SOURCE: "dbname=magma_dev user=magma_dev password=magma_dev host=postgres sslmode=disable"
      SQL_DIALECT: psql

      USE_NEW_HANDLERS: '1'
      USE_NEW_MCONFIGS: '1'

      # To use MariaDB, use these connection parameters instead:
      # SQL_DRIVER: mysql
      # DATABASE_SOURCE: "magma_dev:magma_dev@(maria)/magma_dev"
      # SQL_DIALECT: maria
    restart: always
    depends_on:
      - postgres
      # - maria
    command: ["/bin/sh", "-c", "/usr/local/bin/wait-for-it.sh -s -t 30 postgres:5432 && /usr/bin/supervisord"]
    # command: ["/bin/sh", "-c", "/usr/local/bin/wait-for-it.sh -s -t 30 maria:[port] && /usr/bin/supervisord"]