---
swagger: '2.0'

magma-gen-meta:
  go-package: magma/orc8r/cloud/go/pluginimpl/models
  dependencies:
    - 'orc8r/cloud/go/models/swagger-common.yml'
  temp-gen-filename: orc8r-swagger.yml
  output-dir: orc8r/cloud/go/pluginimpl
  types:
    - go-struct-name: Network
      filename: network_swaggergen.go
    - go-struct-name: NetworkDNSConfig
      filename: network_dns_config_swaggergen.go
    - go-struct-name: DNSConfigRecord
      filename: dns_config_record_swaggergen.go
    - go-struct-name: NetworkFeatures
      filename: network_features_swaggergen.go

info:
  title: Orchestrator Network Management
  description: Orchestrator REST APIs
  version: 1.0.0

basePath: /magma/v1

paths:
  /networks:
    get:
      summary: List all network IDs
      tags:
        - Networks
      responses:
        '200':
          description: List of network IDs
          schema:
            type: array
            items:
              type: string
            example:
              - network1
              - network2
        default:
          $ref: './orc8r-swagger-common.yml#/responses/UnexpectedError'

  /networks/{network_id}:
    get:
      summary: Get a generic network description
      tags:
        - Networks
      parameters:
        - $ref: './orc8r-swagger-common.yml#/parameters/network_id'
      responses:
        '200':
          description: Network description
          schema:
            $ref: '#/definitions/network'
        default:
          $ref: './orc8r-swagger-common.yml#/responses/UnexpectedError'
    delete:
      summary: Delete a network
      tags:
        - Networks
      parameters:
        - $ref: './orc8r-swagger-common.yml#/parameters/network_id'
      responses:
        '204':
          description: Success
        default:
          $ref: './orc8r-swagger-common.yml#/responses/UnexpectedError'

  /networks/{network_id}/type:
    get:
      summary: Get the type of a network
      tags:
        - Networks
      parameters:
        - $ref: './orc8r-swagger-common.yml#/parameters/network_id'
      responses:
        '200':
          description: The type of the network
          schema:
            type: string
            example: 'lte'
        default:
          $ref: './orc8r-swagger-common.yml#/responses/UnexpectedError'
    put:
      summary: Update the type of a network
      tags:
        - Networks
      parameters:
        - $ref: './orc8r-swagger-common.yml#/parameters/network_id'
        - name: type
          in: body
          required: true
          schema:
            type: string
            minLength: 1
            example: 'lte'
      responses:
        '204':
          description: Success
        default:
          $ref: './orc8r-swagger-common.yml#/responses/UnexpectedError'

definitions:
  network:
    type: object
    description: Orchestrator network spec
    required:
      - id
      - name
      - description
      - dns
    properties:
      id:
        $ref: './orc8r-swagger-common.yml#/definitions/network_id'
      name:
        $ref: './orc8r-swagger-common.yml#/definitions/network_name'
      description:
        $ref: './orc8r-swagger-common.yml#/definitions/network_description'
      type:
        description: The type of the network
        type: string
        example: LTE
      dns:
        $ref: '#/definitions/network_dns_config'
      features:
        $ref: '#/definitions/network_features'

  network_dns_config:
    description: DNS configuration for a network
    type: object
    required:
      - enable_caching
      - local_ttl
    properties:
      enable_caching:
        type: boolean
        example: false
      local_ttl:
        type: integer
        format: uint32
        example: 0
      records:
        type: array
        items:
          $ref: '#/definitions/dns_config_record'

  dns_config_record:
    description: Mapping used for DNS resolving from a domain
    type: object
    required:
      - domain
    properties:
      domain:
        type: string
        minLength: 1
        x-nullable: false
        example: example.com
      a_record:
        type: array
        items:
          type: string
          minLength: 1
          x-nullable: false
          example: 192.88.99.142
      aaaa_record:
        type: array
        items:
          type: string
          minLength: 1
          x-nullable: false
          example: 2001:0db8:85a3:0000:0000:8a2e:0370:7334 # TODO: Regex?
      cname_record:
        type: array
        items:
          type: string
          minLength: 1
          x-nullable: false
          example: cname.example.com

  network_features:
    type: object
    description: Feature flags for a network
    properties:
      features:
        type: object
        additionalProperties:
          type: string
        example:
          featureName1: featureProp1
          featureName2: featureProp2
