---
# Install Prometheus AlertManager.

- name: set internal variables for convenience
  set_fact:
    alertmanager_subdir: "{{ alertmanager_subdir }}"

- name: set download url
  set_fact:
    alertmanager_tarball_url: "https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/alertmanager-{{ alertmanager_version }}.{{ prometheus_platform_suffix }}.tar.gz"

- name: set permissions, owner and group
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ promo_user }}"
    group: "{{ promo_group }}"
    mode: "go-w"
    recurse: yes
  with_items:
    - "{{ alertmanager_subdir }}"
    - "{{ alertmanager_db_path }}"
    - "{{ alertmanager_install_path }}"
    - "{{ alert_rules_dir }}"

- name: download and untar alertmanager tarball
  unarchive:
    src: "{{ alertmanager_tarball_url }}"
    dest: "{{ alertmanager_install_path }}"
    copy: no

- name: copy alertmanager main config file
  template:
    src: "alertmanager_conf.yml"
    dest: "{{ alertmanager_subdir }}/alertmanager.yml"
    validate: "{{ alertmanager_subdir }}/amtool check-config %s"

- name: copy alert rules files to prometheus subdir
  copy:
    src: "internal_alert_rules.yml"
    dest: "{{ alert_rules_dir }}/internal_alert_rules.yml"
