---

- name: create magma directory
  file:
    path: "{{ dirLocalInventory }}/magma"
    state: directory

- name: download github repo
  git:
    repo: "{{ buildMagmaRepo }}"
    dest: "{{ dirLocalInventory }}/magma"
    version: "{{ buildMagmaVersion }}"
