---
swagger: '2.0'
info:
  title: Configurator Model Definitions and Paths
  description: Magma REST APIs
  version: 1.0.0

paths:
  /configurator/networks:
    get:
      summary: List all networks
      tags:
      - Networks
      responses:
        '200':
          description: List of network ids
          schema:
            type: array
            items:
              $ref: './swagger-common.yml#/definitions/network_id'
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    post:
      summary: Add a new network
      tags:
      - Networks
      parameters:
      - in: query
        name: requested_id
        type: string
        description: The id of network requested by user
        pattern: '^[a-z_][\da-z_]+$'
        minLength: 1
        maxLength: 100
        required: false
      - in: body
        name: network
        description: Network object that needs to be added
        required: true
        schema:
          $ref: '#/definitions/network_record'
      responses:
        '201':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
  /configurator/networks/{network_id}:
    get:
      summary: Get Network by network ID
      tags:
        - Networks
      parameters:
        - $ref: './swagger-common.yml#/parameters/network_id'
      responses:
        '201':
          description: Network Retrieved
          schema:
            $ref: '#/definitions/network_record'
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    put:
      summary: Update Network
      tags:
        - Networks
      parameters:
        - $ref: './swagger-common.yml#/parameters/network_id'
        - in: body
          name: network
          description: Updated Network
          required: true
          schema:
            $ref: '#/definitions/network_record'
      responses:
        '201':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    delete:
      summary: Delete a network
      tags:
        - Networks
      parameters:
        - $ref: './swagger-common.yml#/parameters/network_id'
      responses:
        '204':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'

parameters:
  config_type:
    type: string
    in: path
    minLength: 1
    description: Config Type
    name: config_type
    required: true

definitions:
  network_record:
      type: object
      required:
      - name
      - description
      properties:
        name:
          type: string
          minLength: 1
          example: "SampleNetwork"
          x-nullable: false
        description:
          type: string
          minLength: 1
          example: "This is a sample network"
          x-nullable: false
