- hosts: kube-master[0]
  become: yes
  become_user: root
  roles:
    - role: magma/mariadb
      when: deploy_mariadb | default(True)
    - role: magma/elasticsearch
      when: deploy_elasticsearch | default(True)
    - role: magma/fluentd
      when: deploy_fluentd | default(True)
    - role: magma/kibana
      when: deploy_kibana | default(False)
    - magma/orc8r
