---
#backing up certs in bootstrap to pass on to AGW

- name: create certs folder on bootstrapper
  file: 
    path: "{{ dirSecretsLocal }}"
    state: directory
    mode: '0755'  

    #TODO: Is this really needed?
- name: install boto3 in local directory
  command: pip install boto3
  args:
    chdir: "{{ dirSecretsLocal }}"

