// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lte/protos/oai/sgw_state.proto

package oai

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// sgw_bearer_context_information
type SgwS8EpsBearerContextInfo struct {
	Imsi                 []byte            `protobuf:"bytes,1,opt,name=imsi,proto3" json:"imsi,omitempty"`
	ImsiUnauthIndicator  uint32            `protobuf:"varint,2,opt,name=imsi_unauth_indicator,json=imsiUnauthIndicator,proto3" json:"imsi_unauth_indicator,omitempty"`
	Msisdn               string            `protobuf:"bytes,3,opt,name=msisdn,proto3" json:"msisdn,omitempty"`
	LastKnownCellId      *Ecgi             `protobuf:"bytes,4,opt,name=last_known_cell_id,json=lastKnownCellId,proto3" json:"last_known_cell_id,omitempty"`
	Trxn                 []byte            `protobuf:"bytes,5,opt,name=trxn,proto3" json:"trxn,omitempty"`
	Imsi64               uint64            `protobuf:"varint,6,opt,name=imsi64,proto3" json:"imsi64,omitempty"`
	MmeTeidS11           uint32            `protobuf:"varint,7,opt,name=mme_teid_s11,json=mmeTeidS11,proto3" json:"mme_teid_s11,omitempty"`
	MmeIpAddressS11      []byte            `protobuf:"bytes,8,opt,name=mme_ip_address_s11,json=mmeIpAddressS11,proto3" json:"mme_ip_address_s11,omitempty"`
	SgwTeidS11S4         uint32            `protobuf:"varint,9,opt,name=sgw_teid_s11_s4,json=sgwTeidS11S4,proto3" json:"sgw_teid_s11_s4,omitempty"`
	SgwIpAddressS11S4    []byte            `protobuf:"bytes,10,opt,name=sgw_ip_address_s11_s4,json=sgwIpAddressS11S4,proto3" json:"sgw_ip_address_s11_s4,omitempty"`
	PdnConnection        *SgwPdnConnection `protobuf:"bytes,11,opt,name=pdn_connection,json=pdnConnection,proto3" json:"pdn_connection,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SgwS8EpsBearerContextInfo) Reset()         { *m = SgwS8EpsBearerContextInfo{} }
func (m *SgwS8EpsBearerContextInfo) String() string { return proto.CompactTextString(m) }
func (*SgwS8EpsBearerContextInfo) ProtoMessage()    {}
func (*SgwS8EpsBearerContextInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_255b0d87855f2347, []int{0}
}

func (m *SgwS8EpsBearerContextInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SgwS8EpsBearerContextInfo.Unmarshal(m, b)
}
func (m *SgwS8EpsBearerContextInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SgwS8EpsBearerContextInfo.Marshal(b, m, deterministic)
}
func (m *SgwS8EpsBearerContextInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SgwS8EpsBearerContextInfo.Merge(m, src)
}
func (m *SgwS8EpsBearerContextInfo) XXX_Size() int {
	return xxx_messageInfo_SgwS8EpsBearerContextInfo.Size(m)
}
func (m *SgwS8EpsBearerContextInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SgwS8EpsBearerContextInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SgwS8EpsBearerContextInfo proto.InternalMessageInfo

func (m *SgwS8EpsBearerContextInfo) GetImsi() []byte {
	if m != nil {
		return m.Imsi
	}
	return nil
}

func (m *SgwS8EpsBearerContextInfo) GetImsiUnauthIndicator() uint32 {
	if m != nil {
		return m.ImsiUnauthIndicator
	}
	return 0
}

func (m *SgwS8EpsBearerContextInfo) GetMsisdn() string {
	if m != nil {
		return m.Msisdn
	}
	return ""
}

func (m *SgwS8EpsBearerContextInfo) GetLastKnownCellId() *Ecgi {
	if m != nil {
		return m.LastKnownCellId
	}
	return nil
}

func (m *SgwS8EpsBearerContextInfo) GetTrxn() []byte {
	if m != nil {
		return m.Trxn
	}
	return nil
}

func (m *SgwS8EpsBearerContextInfo) GetImsi64() uint64 {
	if m != nil {
		return m.Imsi64
	}
	return 0
}

func (m *SgwS8EpsBearerContextInfo) GetMmeTeidS11() uint32 {
	if m != nil {
		return m.MmeTeidS11
	}
	return 0
}

func (m *SgwS8EpsBearerContextInfo) GetMmeIpAddressS11() []byte {
	if m != nil {
		return m.MmeIpAddressS11
	}
	return nil
}

func (m *SgwS8EpsBearerContextInfo) GetSgwTeidS11S4() uint32 {
	if m != nil {
		return m.SgwTeidS11S4
	}
	return 0
}

func (m *SgwS8EpsBearerContextInfo) GetSgwIpAddressS11S4() []byte {
	if m != nil {
		return m.SgwIpAddressS11S4
	}
	return nil
}

func (m *SgwS8EpsBearerContextInfo) GetPdnConnection() *SgwPdnConnection {
	if m != nil {
		return m.PdnConnection
	}
	return nil
}

type SgwUeContext struct {
	SgwBearerContext     []*SgwS8EpsBearerContextInfo `protobuf:"bytes,1,rep,name=sgw_bearer_context,json=sgwBearerContext,proto3" json:"sgw_bearer_context,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *SgwUeContext) Reset()         { *m = SgwUeContext{} }
func (m *SgwUeContext) String() string { return proto.CompactTextString(m) }
func (*SgwUeContext) ProtoMessage()    {}
func (*SgwUeContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_255b0d87855f2347, []int{1}
}

func (m *SgwUeContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SgwUeContext.Unmarshal(m, b)
}
func (m *SgwUeContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SgwUeContext.Marshal(b, m, deterministic)
}
func (m *SgwUeContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SgwUeContext.Merge(m, src)
}
func (m *SgwUeContext) XXX_Size() int {
	return xxx_messageInfo_SgwUeContext.Size(m)
}
func (m *SgwUeContext) XXX_DiscardUnknown() {
	xxx_messageInfo_SgwUeContext.DiscardUnknown(m)
}

var xxx_messageInfo_SgwUeContext proto.InternalMessageInfo

func (m *SgwUeContext) GetSgwBearerContext() []*SgwS8EpsBearerContextInfo {
	if m != nil {
		return m.SgwBearerContext
	}
	return nil
}

type SgwState struct {
	LastTunnelId         uint32   `protobuf:"varint,1,opt,name=last_tunnel_id,json=lastTunnelId,proto3" json:"last_tunnel_id,omitempty"`
	Gtpv1UTeid           uint32   `protobuf:"varint,2,opt,name=gtpv1u_teid,json=gtpv1uTeid,proto3" json:"gtpv1u_teid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SgwState) Reset()         { *m = SgwState{} }
func (m *SgwState) String() string { return proto.CompactTextString(m) }
func (*SgwState) ProtoMessage()    {}
func (*SgwState) Descriptor() ([]byte, []int) {
	return fileDescriptor_255b0d87855f2347, []int{2}
}

func (m *SgwState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SgwState.Unmarshal(m, b)
}
func (m *SgwState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SgwState.Marshal(b, m, deterministic)
}
func (m *SgwState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SgwState.Merge(m, src)
}
func (m *SgwState) XXX_Size() int {
	return xxx_messageInfo_SgwState.Size(m)
}
func (m *SgwState) XXX_DiscardUnknown() {
	xxx_messageInfo_SgwState.DiscardUnknown(m)
}

var xxx_messageInfo_SgwState proto.InternalMessageInfo

func (m *SgwState) GetLastTunnelId() uint32 {
	if m != nil {
		return m.LastTunnelId
	}
	return 0
}

func (m *SgwState) GetGtpv1UTeid() uint32 {
	if m != nil {
		return m.Gtpv1UTeid
	}
	return 0
}

func init() {
	proto.RegisterType((*SgwS8EpsBearerContextInfo)(nil), "magma.lte.oai.SgwS8EpsBearerContextInfo")
	proto.RegisterType((*SgwUeContext)(nil), "magma.lte.oai.SgwUeContext")
	proto.RegisterType((*SgwState)(nil), "magma.lte.oai.SgwState")
}

func init() { proto.RegisterFile("lte/protos/oai/sgw_state.proto", fileDescriptor_255b0d87855f2347) }

var fileDescriptor_255b0d87855f2347 = []byte{
	// 490 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x51, 0x6f, 0xd3, 0x30,
	0x14, 0x85, 0x15, 0x56, 0xca, 0xe6, 0xb6, 0x2b, 0x78, 0x1a, 0x32, 0x93, 0xa0, 0xa1, 0x02, 0x29,
	0x12, 0x52, 0x4b, 0x4b, 0x85, 0x78, 0x84, 0x55, 0x43, 0xaa, 0x78, 0x81, 0x64, 0xe3, 0x81, 0x17,
	0xcb, 0x8b, 0x3d, 0x63, 0x11, 0xdb, 0x51, 0xec, 0x90, 0xf1, 0x53, 0xf9, 0x37, 0xe8, 0x3a, 0x19,
	0x6a, 0x0b, 0x4f, 0xb1, 0xcf, 0x3d, 0xf9, 0x72, 0x72, 0xef, 0x45, 0xcf, 0x0a, 0x2f, 0xe6, 0x65,
	0x65, 0xbd, 0x75, 0x73, 0xcb, 0xd4, 0xdc, 0xc9, 0x86, 0x3a, 0xcf, 0xbc, 0x98, 0x05, 0x11, 0x8f,
	0x34, 0x93, 0x9a, 0xcd, 0x0a, 0x2f, 0x66, 0x96, 0xa9, 0xb3, 0xe7, 0x7b, 0xf6, 0xdc, 0x6a, 0x6d,
	0x0d, 0xf5, 0xbf, 0x4a, 0xe1, 0xda, 0x37, 0xce, 0x26, 0xfb, 0xc4, 0x72, 0x17, 0x39, 0xfd, 0x7d,
	0x80, 0x9e, 0x64, 0xb2, 0xc9, 0xde, 0x5d, 0x94, 0xee, 0x5c, 0xb0, 0x4a, 0x54, 0x6b, 0x6b, 0xbc,
	0xb8, 0xf5, 0x1b, 0x73, 0x63, 0x31, 0x46, 0x3d, 0xa5, 0x9d, 0x22, 0x51, 0x1c, 0x25, 0xc3, 0x34,
	0x9c, 0xf1, 0x12, 0x9d, 0xc2, 0x93, 0xd6, 0x86, 0xd5, 0xfe, 0x3b, 0x55, 0x86, 0xab, 0x9c, 0x79,
	0x5b, 0x91, 0x7b, 0x71, 0x94, 0x8c, 0xd2, 0x13, 0x28, 0x5e, 0x85, 0xda, 0xe6, 0xae, 0x84, 0x1f,
	0xa3, 0xbe, 0x76, 0xca, 0x71, 0x43, 0x0e, 0xe2, 0x28, 0x39, 0x4a, 0xbb, 0x1b, 0x7e, 0x8f, 0x70,
	0xc1, 0x9c, 0xa7, 0x3f, 0x8c, 0x6d, 0x0c, 0xcd, 0x45, 0x51, 0x50, 0xc5, 0x49, 0x2f, 0x8e, 0x92,
	0xc1, 0xf2, 0x64, 0xb6, 0xf3, 0xb7, 0xb3, 0x8b, 0x5c, 0xaa, 0x74, 0x0c, 0xf6, 0x4f, 0xe0, 0x5e,
	0x8b, 0xa2, 0xd8, 0x70, 0x48, 0xe8, 0xab, 0x5b, 0x43, 0xee, 0xb7, 0x09, 0xe1, 0x0c, 0x5f, 0x83,
	0x10, 0x6f, 0x57, 0xa4, 0x1f, 0x47, 0x49, 0x2f, 0xed, 0x6e, 0x38, 0x46, 0x43, 0xad, 0x05, 0xf5,
	0x42, 0x71, 0xea, 0x16, 0x0b, 0xf2, 0x20, 0x04, 0x46, 0x5a, 0x8b, 0x4b, 0xa1, 0x78, 0xb6, 0x58,
	0xe0, 0x57, 0x08, 0x83, 0x43, 0x95, 0x94, 0x71, 0x5e, 0x09, 0xe7, 0x82, 0xef, 0x30, 0xb0, 0xc7,
	0x5a, 0x8b, 0x4d, 0xf9, 0xa1, 0xd5, 0xc1, 0xfc, 0x12, 0x8d, 0x61, 0x40, 0x77, 0x38, 0xea, 0x56,
	0xe4, 0x28, 0x10, 0x87, 0x4e, 0x36, 0x1d, 0x31, 0x5b, 0xe1, 0xd7, 0xe8, 0x14, 0x6c, 0xbb, 0x4c,
	0x30, 0xa3, 0x80, 0x7d, 0xe4, 0x64, 0xb3, 0x8d, 0xcd, 0x56, 0xf8, 0x23, 0x3a, 0x2e, 0xb9, 0xa1,
	0xb9, 0x35, 0x46, 0xe4, 0x5e, 0x59, 0x43, 0x06, 0xa1, 0x23, 0x93, 0xbd, 0x8e, 0x64, 0xb2, 0xf9,
	0xcc, 0xcd, 0xfa, 0xaf, 0x2d, 0x1d, 0x95, 0xdb, 0xd7, 0xe9, 0x0d, 0x1a, 0x66, 0xb2, 0xb9, 0x12,
	0xdd, 0x44, 0xf1, 0x57, 0x84, 0x21, 0xc9, 0x75, 0x18, 0x33, 0xe0, 0x41, 0x25, 0x51, 0x7c, 0x90,
	0x0c, 0x96, 0xc9, 0xbf, 0xec, 0xff, 0xef, 0x44, 0xfa, 0xd0, 0xc9, 0x66, 0x47, 0x9d, 0x7e, 0x41,
	0x87, 0x60, 0x87, 0xad, 0xc2, 0x2f, 0xd0, 0x71, 0x98, 0xa8, 0xaf, 0x8d, 0x11, 0x61, 0x9a, 0x51,
	0xdb, 0x13, 0x50, 0x2f, 0x83, 0xb8, 0xe1, 0x78, 0x82, 0x06, 0xd2, 0x97, 0x3f, 0x17, 0x75, 0xe8,
	0x5e, 0xb7, 0x39, 0xa8, 0x95, 0xa0, 0x73, 0xe7, 0x93, 0x6f, 0x4f, 0x43, 0x9e, 0x39, 0xec, 0x6f,
	0x5e, 0xd8, 0x9a, 0xcf, 0xa5, 0xdd, 0x5a, 0xe4, 0xeb, 0x7e, 0x38, 0xbf, 0xf9, 0x13, 0x00, 0x00,
	0xff, 0xff, 0x6b, 0x2c, 0x9e, 0xb7, 0x33, 0x03, 0x00, 0x00,
}
