---
swagger: '2.0'
info:
  title: Checkind Model Definitions and Paths
  description: Magma REST APIs
  version: 1.0.0

paths:
  /networks/{network_id}/gateways/{gateway_id}/status:
    get:
      summary: Retrieve Gateway Status
      tags:
      - Gateways
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - $ref: './swagger-common.yml#/parameters/gateway_id'
      responses:
        '200':
          description: Requested Gateway Status
          schema:
            $ref: '#/definitions/gateway_status'
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'

definitions:
  disk_partition:
    type: object
    properties:
      device:
        type: string
      mount_point:
        type: string
      total:
        type: integer
        format: uint64
      used:
        type: integer
        format: uint64
      free:
        type: integer
        format: uint64
  system_status:
    type: object
    properties:
      time:
        type: integer
        format: uint64
        example: 1234567000
      uptime_secs:
        type: integer
        format: uint64
        example: 12345
      cpu_user:
        type: integer
        format: uint64
        x-go-custom-tag: 'magma_alt_name:"CpuUser"'
      cpu_system:
        type: integer
        format: uint64
        x-go-custom-tag: 'magma_alt_name:"CpuSystem"'
      cpu_idle:
        type: integer
        format: uint64
        x-go-custom-tag: 'magma_alt_name:"CpuIdle"'
      mem_total:
        type: integer
        format: uint64
      mem_available:
        type: integer
        format: uint64
      mem_used:
        type: integer
        format: uint64
      mem_free:
        type: integer
        format: uint64
      swap_total:
        type: integer
        format: uint64
      swap_used:
        type: integer
        format: uint64
      swap_free:
        type: integer
        format: uint64
      disk_partitions:
        type: array
        x-omitempty: true
        items:
          $ref: '#/definitions/disk_partition'
  package:
    type: object
    properties:
      name:
        type: string
        example: magma
      version:
        type: string
        example: 0.0.0
  platform_info:
    type: object
    properties:
      vpn_ip:
        type: string
        example: 10.0.0.1
        x-go-custom-tag: 'magma_alt_name:"VpnIp"'
      packages:
        type: array
        x-omitempty: true
        items:
          $ref: '#/definitions/package'
      kernel_version:
        type: string
        example: 4.9.0-6-amd64
      kernel_versions_installed:
        type: array
        x-omitempty: true
        items:
          type: string
        example: ["4.9.0-6-amd64", "4.9.0-7-amd64"]
  network_interface:
    type: object
    properties:
      network_interface_id:
        type: string
        example: gtp_br0
        x-go-custom-tag: 'magma_alt_name:"NetworkInterfaceId"'
      status:
        type: string
        enum:
        - UP
        - DOWN
        - UNKNOWN
        example: UP
      mac_address:
        type: string
        example: 08:00:27:1e:8a:32
      ip_addresses:
        type: array
        x-omitempty: true
        items:
          type: string
        example: ['10.10.10.1', '10.0.0.1']
        x-go-custom-tag: 'magma_alt_name:"IpAddresses"'
      ipv6_addresses:
        type: array
        x-omitempty: true
        items:
          type: string
        example: ['fe80::a00:27ff:fe1e:8332', 'fe80::a00:27ff:fe1e:8432']
        x-go-custom-tag: 'magma_alt_name:"Ipv6Addresses"'
  route:
    type: object
    properties:
      destination_ip:
        type: string
        example: 0.0.0.0
        x-go-custom-tag: 'magma_alt_name:"DestinationIp"'
      gateway_ip:
        type: string
        example: 10.10.10.1
        x-go-custom-tag: 'magma_alt_name:"GatewayIp"'
      genmask:
        type: string
        example: 255.255.255.0
      network_interface_id:
        type: string
        example: gtp_br0
        x-go-custom-tag: 'magma_alt_name:"NetworkInterfaceId"'
  machine_info:
    type: object
    properties:
      cpu_info:
        type: object
        properties:
          core_count:
            type: integer
            format: uint64
            example: 4
          threads_per_core:
            type: integer
            format: uint64
            example: 1
          architecture:
            type: string
            example: x86_64
          model_name:
            type: string
            example: Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
      network_info:
        type: object
        properties:
          network_interfaces:
            type: array
            x-omitempty: true
            items:
              $ref: '#/definitions/network_interface'
          routing_table:
            type: array
            x-omitempty: true
            items:
              $ref: '#/definitions/route'
  gateway_status:
    type: object
    properties:
      checkin_time:
        type: integer
        format: uint64
        example: 1234567890
      hardware_id:
        type: string
      version:
        type: string
        description: deprecated
      system_status:
        $ref: '#/definitions/system_status'
      platform_info:
        $ref: '#/definitions/platform_info'
      machine_info:
        $ref: '#/definitions/machine_info'
      cert_expiration_time:
        type: integer
        format: int64
        example: 1234567890
      meta:
        type: object
        additionalProperties:
          type: string
      vpn_ip:
        type: string
        example: 10.0.0.1
        description: deprecated
      kernel_version:
        type: string
        example: 4.9.0-6-amd64
        description: deprecated
      kernel_versions_installed:
        type: array
        x-omitempty: true
        items:
          type: string
        example: ["4.9.0-6-amd64", "4.9.0-7-amd64"]
        description: deprecated