---
# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

- name: Install python
  hosts: magma-cloud-dev
  gather_facts: False
  tasks:
    - name: Install python 2
      raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)

- name: Set up development pre-reqs on a local machine
  hosts: magma-cloud-dev
  become: yes
  environment:
    DEBIAN_FRONTEND: "noninteractive"
    http_proxy: "{{ http_proxy | default('') }}"
    https_proxy: "{{ https_proxy | default('') }}"

  vars:
    user: "{{ ansible_user }}"
    magma_root: "/home/{{ user }}/magma"
    restart_controller: false
    controller_hostname: controller.magma.test
    api_hostname: api.magma.test
    proxy_backends: "127.0.0.1,::1"
    feg_backends: "127.0.0.1,::1"
    apt_cache_directory: "{{ magma_root }}/.cache/magma-cloud-dev/apt/archives"

    # Set both variables below to true to provision from a blank box
    # Set preburn to true if you want to run the preburn tasks
    preburn: false
    # Set full_provision to true if you want to run the post-preburn tasks
    full_provision: true

  roles:
    - { role: apt_package_cache, when: ansible_user == 'vagrant'}
    - { role: pkgrepo, vars: { distribution: "xenial" } }
    - { role: modules }
    - { role: dev }
    - { role: service_registry}
    - { role: golang }
    - { role: proxy }
    - { role: controller }
    - { role: dynamodb }
