---
- name: Set up the controller production instance using Docker
  hosts: localhost
  become: yes

  vars:
    user: '{{ ansible_user }}'

  roles:
    - role: docker
      vars:
        systemd_service: magma@controller
        image_names: [controller]
        compose_file: docker/docker-compose.controller.yml
