---
- name: Set up the proxy production instance using Docker
  hosts: localhost
  become: yes

  vars:
    user: '{{ ansible_user }}'

  roles:
    - role: docker
      vars:
        systemd_service: magma@proxy
        image_names: [proxy]
        compose_file: docker/docker-compose.proxy.yml