---
swagger: '2.0'
info:
  title: Magma Carrier WiFi Configuration
  description: Magma REST APIs
  version: 1.1.2

paths:
  /networks/{network_id}/configs/carrier_wifi:
    post:
      summary: Create Network Carrier Wifi Configs
      tags:
      - Networks
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - in: body
        name: config
        description: New config
        required: true
        schema:
          $ref: '#/definitions/network_carrier_wifi_configs'
      responses:
        '201':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    get:
      summary: Retrieve Network Carrier Wifi Configs
      tags:
      - Networks
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      responses:
        '200':
          description: Retrieve Network Carrier Wifi Configs
          schema:
            $ref: '#/definitions/network_carrier_wifi_configs'
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    put:
      summary: Modify Network Carrier Wifi Configs
      tags:
      - Networks
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - in: body
        name: config
        description: Updated config
        required: true
        schema:
          $ref: '#/definitions/network_carrier_wifi_configs'
      responses:
        '200':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    delete:
      summary: Delete Network Carrier Wifi Configs
      tags:
      - Networks
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      responses:
        '204':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'

definitions:
  network_carrier_wifi_configs:
    description: Carrier WiFi configuration for a network
    type: object
    minLength: 1
    properties:
      nat_enabled:
        type: boolean
        example: true
      relay_enabled:
        type: boolean
        example: true
      default_rule_id:
        type: string
        example: 'default_rule_1'
      network_services:
        description: Configuration for network services. Services will be instantiated in the listed order.
        type: array
        x-omitempty: true
        items:
          type: string
          enum:
            - 'metering'
            - 'dpi'
            - 'policy_enforcement'
        example:
          - 'policy_enforcement'
      eap_aka:
        type: object
        properties:
          timeout:
            $ref: '#/definitions/eap_aka_timeouts'
          plmn_ids:
            type: array
            items:
              type: string
              minLength: 5
              maxLength: 6
              pattern: '^(\d{5,6})$'
              example: '123456'
      aaa_server:
        type: object
        properties:
          idle_session_timeout_ms:
            type: integer
            format: uint32
            x-nullable: false
            example: 21600000
            default: 21600000
            x-go-custom-tag: 'magma_alt_name:"IdleSessionTimeoutMs"'
          accounting_enabled:
            type: boolean
            x-nullable: false
            example: false
            default: false
          create_session_on_auth:
            type: boolean
            x-nullable: false
            example: false
            default: false
      feg_network_id:
        type: string
        example: "example_feg_network"

  eap_aka_timeouts:
    type: object
    properties:
      challenge_ms:
        type: integer
        format: uint32
        x-nullable: false
        default: 20000
        example: 20000
      error_notification_ms:
        type: integer
        format: uint32
        x-nullable: false
        default: 10000
        example: 10000
      session_ms:
        type: integer
        format: uint32
        x-nullable: false
        default: 43200000
        example: 43200000
      session_authenticated_ms:
        type: integer
        format: uint32
        x-nullable: false
        default: 5000
        example: 5000
