// Code generated by go-swagger; DO NOT EDIT.

package wifi_meshes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"magma/orc8r/cloud/go/obsidian/swagger/v1/models"
)

// NewPutWifiNetworkIDMeshesMeshIDConfigParams creates a new PutWifiNetworkIDMeshesMeshIDConfigParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutWifiNetworkIDMeshesMeshIDConfigParams() *PutWifiNetworkIDMeshesMeshIDConfigParams {
	return &PutWifiNetworkIDMeshesMeshIDConfigParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutWifiNetworkIDMeshesMeshIDConfigParamsWithTimeout creates a new PutWifiNetworkIDMeshesMeshIDConfigParams object
// with the ability to set a timeout on a request.
func NewPutWifiNetworkIDMeshesMeshIDConfigParamsWithTimeout(timeout time.Duration) *PutWifiNetworkIDMeshesMeshIDConfigParams {
	return &PutWifiNetworkIDMeshesMeshIDConfigParams{
		timeout: timeout,
	}
}

// NewPutWifiNetworkIDMeshesMeshIDConfigParamsWithContext creates a new PutWifiNetworkIDMeshesMeshIDConfigParams object
// with the ability to set a context for a request.
func NewPutWifiNetworkIDMeshesMeshIDConfigParamsWithContext(ctx context.Context) *PutWifiNetworkIDMeshesMeshIDConfigParams {
	return &PutWifiNetworkIDMeshesMeshIDConfigParams{
		Context: ctx,
	}
}

// NewPutWifiNetworkIDMeshesMeshIDConfigParamsWithHTTPClient creates a new PutWifiNetworkIDMeshesMeshIDConfigParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutWifiNetworkIDMeshesMeshIDConfigParamsWithHTTPClient(client *http.Client) *PutWifiNetworkIDMeshesMeshIDConfigParams {
	return &PutWifiNetworkIDMeshesMeshIDConfigParams{
		HTTPClient: client,
	}
}

/* PutWifiNetworkIDMeshesMeshIDConfigParams contains all the parameters to send to the API endpoint
   for the put wifi network ID meshes mesh ID config operation.

   Typically these are written to a http.Request.
*/
type PutWifiNetworkIDMeshesMeshIDConfigParams struct {

	/* MeshID.

	   Mesh ID
	*/
	MeshID string

	/* MeshWifiConfigs.

	   The updated wifi configs of the mesh
	*/
	MeshWifiConfigs *models.MeshWifiConfigs

	/* NetworkID.

	   Network ID
	*/
	NetworkID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put wifi network ID meshes mesh ID config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutWifiNetworkIDMeshesMeshIDConfigParams) WithDefaults() *PutWifiNetworkIDMeshesMeshIDConfigParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put wifi network ID meshes mesh ID config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutWifiNetworkIDMeshesMeshIDConfigParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put wifi network ID meshes mesh ID config params
func (o *PutWifiNetworkIDMeshesMeshIDConfigParams) WithTimeout(timeout time.Duration) *PutWifiNetworkIDMeshesMeshIDConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put wifi network ID meshes mesh ID config params
func (o *PutWifiNetworkIDMeshesMeshIDConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put wifi network ID meshes mesh ID config params
func (o *PutWifiNetworkIDMeshesMeshIDConfigParams) WithContext(ctx context.Context) *PutWifiNetworkIDMeshesMeshIDConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put wifi network ID meshes mesh ID config params
func (o *PutWifiNetworkIDMeshesMeshIDConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put wifi network ID meshes mesh ID config params
func (o *PutWifiNetworkIDMeshesMeshIDConfigParams) WithHTTPClient(client *http.Client) *PutWifiNetworkIDMeshesMeshIDConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put wifi network ID meshes mesh ID config params
func (o *PutWifiNetworkIDMeshesMeshIDConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMeshID adds the meshID to the put wifi network ID meshes mesh ID config params
func (o *PutWifiNetworkIDMeshesMeshIDConfigParams) WithMeshID(meshID string) *PutWifiNetworkIDMeshesMeshIDConfigParams {
	o.SetMeshID(meshID)
	return o
}

// SetMeshID adds the meshId to the put wifi network ID meshes mesh ID config params
func (o *PutWifiNetworkIDMeshesMeshIDConfigParams) SetMeshID(meshID string) {
	o.MeshID = meshID
}

// WithMeshWifiConfigs adds the meshWifiConfigs to the put wifi network ID meshes mesh ID config params
func (o *PutWifiNetworkIDMeshesMeshIDConfigParams) WithMeshWifiConfigs(meshWifiConfigs *models.MeshWifiConfigs) *PutWifiNetworkIDMeshesMeshIDConfigParams {
	o.SetMeshWifiConfigs(meshWifiConfigs)
	return o
}

// SetMeshWifiConfigs adds the meshWifiConfigs to the put wifi network ID meshes mesh ID config params
func (o *PutWifiNetworkIDMeshesMeshIDConfigParams) SetMeshWifiConfigs(meshWifiConfigs *models.MeshWifiConfigs) {
	o.MeshWifiConfigs = meshWifiConfigs
}

// WithNetworkID adds the networkID to the put wifi network ID meshes mesh ID config params
func (o *PutWifiNetworkIDMeshesMeshIDConfigParams) WithNetworkID(networkID string) *PutWifiNetworkIDMeshesMeshIDConfigParams {
	o.SetNetworkID(networkID)
	return o
}

// SetNetworkID adds the networkId to the put wifi network ID meshes mesh ID config params
func (o *PutWifiNetworkIDMeshesMeshIDConfigParams) SetNetworkID(networkID string) {
	o.NetworkID = networkID
}

// WriteToRequest writes these params to a swagger request
func (o *PutWifiNetworkIDMeshesMeshIDConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param mesh_id
	if err := r.SetPathParam("mesh_id", o.MeshID); err != nil {
		return err
	}
	if o.MeshWifiConfigs != nil {
		if err := r.SetBodyParam(o.MeshWifiConfigs); err != nil {
			return err
		}
	}

	// path param network_id
	if err := r.SetPathParam("network_id", o.NetworkID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
