---
# Copyright 2020 The Magma Authors.

# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
analytics:
  aggrMetricThreshold: 100
  metrics:
    subscriber_attach_success_percent:
      register: false
      export: false
      enforceMinThreshold: true
      class:
        - reliability
      expr: round((sum by(gatewayID) (increase(ue_attach{action="attach_accept_sent"}[3h]))) * 100 / (sum by(gatewayID) (increase(ue_attach{action=~"attach_accept_sent|attach_reject_sent|attach_abort"}[3h]))))

    subscriber_attach_reject_percent:
      register: false
      export: false
      enforceMinThreshold: true
      class:
        - reliability
      expr: round((sum by(gatewayID) (increase(ue_attach{action="attach_reject_sent"}[3h]))) * 100 / (sum by(gatewayID) (increase(ue_attach{action=~"attach_accept_sent|attach_reject_sent|attach_abort"}[3h]))))

    subscriber_duplicate_attach_count:
      register: false
      export: false
      enforceMinThreshold: true
      class:
        - reliability
      expr: sum(duplicate_attach_request) by (networkID, gatewayID)

    service_request_success_percent:
      register: false
      export: false
      enforceMinThreshold: true
      class:
        - reliability
      expr: round((sum by(networkID) (increase(service_request{result="success"}[3h]))) *100 / ((sum by(networkID)(increase(service_request{result="failure"}[3h]))) + (sum by(networkID) (increase(service_request{ result="success"}[3h])))))

    session_create_success_percent:
      register: false
      export: false
      enforceMinThreshold: true
      class:
        - reliability
      expr: round((sum by(networkID) (increase(mme_spgw_create_session_rsp{result="success"}[3h]) * 100)) / (sum by(networkID) (increase(mme_spgw_create_session_rsp[3h]))))

    backhaul_latency:
      register: false
      export: false
      class:
        - reliability
      expr: sum(magmad_ping_rtt_ms{service="magmad",host="8.8.8.8",metric="rtt_ms"}) by (gatewayID, networkID)

    gateway_throughput:
      register: false
      export: false
      class:
        - network
      expr: sum(gtp_port_user_plane_dl_bytes) by (gatewayID)

    enodeb_throughput:
      register: false
      export: false
      enforceMinThreshold: true
      class:
        - network
      expr: sum(gtp_port_user_plane_dl_bytes) by (gatewayID, ip_addr)

    connected_ues:
      register: false
      export: false
      enforceMinThreshold: true
      class:
        - network
      expr: sum(ue_connected) by (gatewayID, networkID)

    unique_subscribers:
      register: false
      export: false
      enforceMinThreshold: true
      class:
        - engagement
      expr: sum(group(ue_reported_usage) by (IMSI))

    new_subscribers:
      register: false
      export: false
      enforceMinThreshold: true
      class:
        - engagement
      expr: sum(group(ue_reported_usage) by (IMSI)  unless group(ue_reported_usage offset 1d) by (IMSI))

    ue_throughput_ul_avg:
      register: false
      export: false
      enforceMinThreshold: true
      class:
        - engagement
      expr: avg(rate(ue_reported_usage{direction="up"}[3h]))

    ue_throughput_dl_avg:
      register: false
      export: false
      enforceMinThreshold: true
      class:
        - engagement
      expr: sum(avg_over_time(ue_reported_usage{direction="up"}[3h])) by (IMSI)