apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-pre-install-checks
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
data:
  dns_domain: {{ required "dnsDomain must be provided" .Values.dnsDomain }}
{{- if .Capabilities.APIVersions.Has "cert-manager.io/v1" }}
  cert_manager: "cert-manager is installed"
{{- else }}
  cert_manager: {{ required "Please install cert-manager from https://cert-manager.io/docs/installation/kubernetes/" .Values.certManager }}
{{- end }}
