---

- include: ansible-setup.yaml
  become: yes
  tags: setupPackages
- include: magma-setup.yaml
  become: yes
  tags: setupMagma
- include: agw-setup.yaml
  become: yes
  tags: setupAgw
- include: magma-cleanup.yaml
  become: yes
  tags: cleanupMagmaAgw
