// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lte/protos/subscriberauth.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ErrorCode reflects Experimental-Result values which are 3GPP failures
// to be processed by EPC. Diameter Base Protocol errors are reflected in gRPC status code
type M5GErrorCode int32

const (
	M5GErrorCode_UNDEFINED M5GErrorCode = 0
	// Default success code
	M5GErrorCode_MULTI_ROUND_AUTH        M5GErrorCode = 1001
	M5GErrorCode_SUCCESS                 M5GErrorCode = 2001
	M5GErrorCode_LIMITED_SUCCESS         M5GErrorCode = 2002
	M5GErrorCode_COMMAND_UNSUPORTED      M5GErrorCode = 3001
	M5GErrorCode_UNABLE_TO_DELIVER       M5GErrorCode = 3002
	M5GErrorCode_REALM_NOT_SERVED        M5GErrorCode = 3003
	M5GErrorCode_TOO_BUSY                M5GErrorCode = 3004
	M5GErrorCode_LOOP_DETECTED           M5GErrorCode = 3005
	M5GErrorCode_REDIRECT_INDICATION     M5GErrorCode = 3006
	M5GErrorCode_APPLICATION_UNSUPPORTED M5GErrorCode = 3007
	M5GErrorCode_INVALIDH_DR_BITS        M5GErrorCode = 3008
	M5GErrorCode_INVALID_AVP_BITS        M5GErrorCode = 3009
	M5GErrorCode_UNKNOWN_PEER            M5GErrorCode = 3010
	M5GErrorCode_AUTHENTICATION_REJECTED M5GErrorCode = 4001
	M5GErrorCode_OUT_OF_SPACE            M5GErrorCode = 4002
	M5GErrorCode_ELECTION_LOST           M5GErrorCode = 4003
	M5GErrorCode_AUTHORIZATION_REJECTED  M5GErrorCode = 5003
	// Permanent Failures 7.4.3
	M5GErrorCode_USER_UNKNOWN             M5GErrorCode = 5001
	M5GErrorCode_UNKNOWN_SESSION_ID       M5GErrorCode = 5002
	M5GErrorCode_UNKNOWN_EPS_SUBSCRIPTION M5GErrorCode = 5420
	M5GErrorCode_RAT_NOT_ALLOWED          M5GErrorCode = 5421
	M5GErrorCode_ROAMING_NOT_ALLOWED      M5GErrorCode = 5004
	M5GErrorCode_EQUIPMENT_UNKNOWN        M5GErrorCode = 5422
	M5GErrorCode_UNKOWN_SERVING_NODE      M5GErrorCode = 5423
	// Transient Failures 7.4.4
	M5GErrorCode_AUTHENTICATION_DATA_UNAVAILABLE M5GErrorCode = 4181
)

var M5GErrorCode_name = map[int32]string{
	0:    "UNDEFINED",
	1001: "MULTI_ROUND_AUTH",
	2001: "SUCCESS",
	2002: "LIMITED_SUCCESS",
	3001: "COMMAND_UNSUPORTED",
	3002: "UNABLE_TO_DELIVER",
	3003: "REALM_NOT_SERVED",
	3004: "TOO_BUSY",
	3005: "LOOP_DETECTED",
	3006: "REDIRECT_INDICATION",
	3007: "APPLICATION_UNSUPPORTED",
	3008: "INVALIDH_DR_BITS",
	3009: "INVALID_AVP_BITS",
	3010: "UNKNOWN_PEER",
	4001: "AUTHENTICATION_REJECTED",
	4002: "OUT_OF_SPACE",
	4003: "ELECTION_LOST",
	5003: "AUTHORIZATION_REJECTED",
	5001: "USER_UNKNOWN",
	5002: "UNKNOWN_SESSION_ID",
	5420: "UNKNOWN_EPS_SUBSCRIPTION",
	5421: "RAT_NOT_ALLOWED",
	5004: "ROAMING_NOT_ALLOWED",
	5422: "EQUIPMENT_UNKNOWN",
	5423: "UNKOWN_SERVING_NODE",
	4181: "AUTHENTICATION_DATA_UNAVAILABLE",
}

var M5GErrorCode_value = map[string]int32{
	"UNDEFINED":                       0,
	"MULTI_ROUND_AUTH":                1001,
	"SUCCESS":                         2001,
	"LIMITED_SUCCESS":                 2002,
	"COMMAND_UNSUPORTED":              3001,
	"UNABLE_TO_DELIVER":               3002,
	"REALM_NOT_SERVED":                3003,
	"TOO_BUSY":                        3004,
	"LOOP_DETECTED":                   3005,
	"REDIRECT_INDICATION":             3006,
	"APPLICATION_UNSUPPORTED":         3007,
	"INVALIDH_DR_BITS":                3008,
	"INVALID_AVP_BITS":                3009,
	"UNKNOWN_PEER":                    3010,
	"AUTHENTICATION_REJECTED":         4001,
	"OUT_OF_SPACE":                    4002,
	"ELECTION_LOST":                   4003,
	"AUTHORIZATION_REJECTED":          5003,
	"USER_UNKNOWN":                    5001,
	"UNKNOWN_SESSION_ID":              5002,
	"UNKNOWN_EPS_SUBSCRIPTION":        5420,
	"RAT_NOT_ALLOWED":                 5421,
	"ROAMING_NOT_ALLOWED":             5004,
	"EQUIPMENT_UNKNOWN":               5422,
	"UNKOWN_SERVING_NODE":             5423,
	"AUTHENTICATION_DATA_UNAVAILABLE": 4181,
}

func (x M5GErrorCode) String() string {
	return proto.EnumName(M5GErrorCode_name, int32(x))
}

func (M5GErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6a742c81ad67f98d, []int{0}
}

// Authentication Information Request (Section 7.2.5)
type M5GAuthenticationInformationRequest struct {
	// Subscriber identifier
	UserName string `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	// Visted site identifier
	VisitedPlmn []byte `protobuf:"bytes,2,opt,name=visited_plmn,json=visitedPlmn,proto3" json:"visited_plmn,omitempty"`
	// Number of vectors to request in response
	NumRequestedM5GauthVectors uint32 `protobuf:"varint,3,opt,name=num_requested_m5gauth_vectors,json=numRequestedM5gauthVectors,proto3" json:"num_requested_m5gauth_vectors,omitempty"`
	// Indicates to the HSS the values are requested for immediate attach
	ImmediateResponsePreferred bool `protobuf:"varint,4,opt,name=immediate_response_preferred,json=immediateResponsePreferred,proto3" json:"immediate_response_preferred,omitempty"`
	// Concatenation of RAND and AUTS in the case of a resync attach case
	ResyncInfo []byte `protobuf:"bytes,5,opt,name=resync_info,json=resyncInfo,proto3" json:"resync_info,omitempty"`
	// Number of UTRAN/GERAN vectors to request in response (optional)
	NumRequestedUtranGeranVectors uint32 `protobuf:"varint,6,opt,name=num_requested_utran_geran_vectors,json=numRequestedUtranGeranVectors,proto3" json:"num_requested_utran_geran_vectors,omitempty"`
	// UTRAN/GERAN Resync Info (optional)
	UtranGeranResyncInfo []byte `protobuf:"bytes,7,opt,name=utran_geran_resync_info,json=utranGeranResyncInfo,proto3" json:"utran_geran_resync_info,omitempty"`
	// Name of the serving network
	ServingNetworkName   string   `protobuf:"bytes,8,opt,name=serving_network_name,json=servingNetworkName,proto3" json:"serving_network_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M5GAuthenticationInformationRequest) Reset()         { *m = M5GAuthenticationInformationRequest{} }
func (m *M5GAuthenticationInformationRequest) String() string { return proto.CompactTextString(m) }
func (*M5GAuthenticationInformationRequest) ProtoMessage()    {}
func (*M5GAuthenticationInformationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a742c81ad67f98d, []int{0}
}

func (m *M5GAuthenticationInformationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M5GAuthenticationInformationRequest.Unmarshal(m, b)
}
func (m *M5GAuthenticationInformationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M5GAuthenticationInformationRequest.Marshal(b, m, deterministic)
}
func (m *M5GAuthenticationInformationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M5GAuthenticationInformationRequest.Merge(m, src)
}
func (m *M5GAuthenticationInformationRequest) XXX_Size() int {
	return xxx_messageInfo_M5GAuthenticationInformationRequest.Size(m)
}
func (m *M5GAuthenticationInformationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_M5GAuthenticationInformationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_M5GAuthenticationInformationRequest proto.InternalMessageInfo

func (m *M5GAuthenticationInformationRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *M5GAuthenticationInformationRequest) GetVisitedPlmn() []byte {
	if m != nil {
		return m.VisitedPlmn
	}
	return nil
}

func (m *M5GAuthenticationInformationRequest) GetNumRequestedM5GauthVectors() uint32 {
	if m != nil {
		return m.NumRequestedM5GauthVectors
	}
	return 0
}

func (m *M5GAuthenticationInformationRequest) GetImmediateResponsePreferred() bool {
	if m != nil {
		return m.ImmediateResponsePreferred
	}
	return false
}

func (m *M5GAuthenticationInformationRequest) GetResyncInfo() []byte {
	if m != nil {
		return m.ResyncInfo
	}
	return nil
}

func (m *M5GAuthenticationInformationRequest) GetNumRequestedUtranGeranVectors() uint32 {
	if m != nil {
		return m.NumRequestedUtranGeranVectors
	}
	return 0
}

func (m *M5GAuthenticationInformationRequest) GetUtranGeranResyncInfo() []byte {
	if m != nil {
		return m.UtranGeranResyncInfo
	}
	return nil
}

func (m *M5GAuthenticationInformationRequest) GetServingNetworkName() string {
	if m != nil {
		return m.ServingNetworkName
	}
	return ""
}

// Authentication Information Answer (Section 7.2.6)
type M5GAuthenticationInformationAnswer struct {
	// EPC error code on failure
	ErrorCode M5GErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=magma.lte.M5GErrorCode" json:"error_code,omitempty"`
	// Authentication vectors matching the requested number
	M5GauthVectors       []*M5GAuthenticationInformationAnswer_M5GAuthenticationVector `protobuf:"bytes,2,rep,name=m5gauth_vectors,json=m5gauthVectors,proto3" json:"m5gauth_vectors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                      `json:"-"`
	XXX_unrecognized     []byte                                                        `json:"-"`
	XXX_sizecache        int32                                                         `json:"-"`
}

func (m *M5GAuthenticationInformationAnswer) Reset()         { *m = M5GAuthenticationInformationAnswer{} }
func (m *M5GAuthenticationInformationAnswer) String() string { return proto.CompactTextString(m) }
func (*M5GAuthenticationInformationAnswer) ProtoMessage()    {}
func (*M5GAuthenticationInformationAnswer) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a742c81ad67f98d, []int{1}
}

func (m *M5GAuthenticationInformationAnswer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M5GAuthenticationInformationAnswer.Unmarshal(m, b)
}
func (m *M5GAuthenticationInformationAnswer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M5GAuthenticationInformationAnswer.Marshal(b, m, deterministic)
}
func (m *M5GAuthenticationInformationAnswer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M5GAuthenticationInformationAnswer.Merge(m, src)
}
func (m *M5GAuthenticationInformationAnswer) XXX_Size() int {
	return xxx_messageInfo_M5GAuthenticationInformationAnswer.Size(m)
}
func (m *M5GAuthenticationInformationAnswer) XXX_DiscardUnknown() {
	xxx_messageInfo_M5GAuthenticationInformationAnswer.DiscardUnknown(m)
}

var xxx_messageInfo_M5GAuthenticationInformationAnswer proto.InternalMessageInfo

func (m *M5GAuthenticationInformationAnswer) GetErrorCode() M5GErrorCode {
	if m != nil {
		return m.ErrorCode
	}
	return M5GErrorCode_UNDEFINED
}

func (m *M5GAuthenticationInformationAnswer) GetM5GauthVectors() []*M5GAuthenticationInformationAnswer_M5GAuthenticationVector {
	if m != nil {
		return m.M5GauthVectors
	}
	return nil
}

// 3GPP TS 29.272, 7.3.18 E-UTRAN-Vector
// For details about fields read 3GPP 33.401
type M5GAuthenticationInformationAnswer_M5GAuthenticationVector struct {
	Rand                 []byte   `protobuf:"bytes,1,opt,name=rand,proto3" json:"rand,omitempty"`
	XresStar             []byte   `protobuf:"bytes,2,opt,name=xres_star,json=xresStar,proto3" json:"xres_star,omitempty"`
	Autn                 []byte   `protobuf:"bytes,3,opt,name=autn,proto3" json:"autn,omitempty"`
	Kseaf                []byte   `protobuf:"bytes,4,opt,name=kseaf,proto3" json:"kseaf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M5GAuthenticationInformationAnswer_M5GAuthenticationVector) Reset() {
	*m = M5GAuthenticationInformationAnswer_M5GAuthenticationVector{}
}
func (m *M5GAuthenticationInformationAnswer_M5GAuthenticationVector) String() string {
	return proto.CompactTextString(m)
}
func (*M5GAuthenticationInformationAnswer_M5GAuthenticationVector) ProtoMessage() {}
func (*M5GAuthenticationInformationAnswer_M5GAuthenticationVector) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a742c81ad67f98d, []int{1, 0}
}

func (m *M5GAuthenticationInformationAnswer_M5GAuthenticationVector) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M5GAuthenticationInformationAnswer_M5GAuthenticationVector.Unmarshal(m, b)
}
func (m *M5GAuthenticationInformationAnswer_M5GAuthenticationVector) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M5GAuthenticationInformationAnswer_M5GAuthenticationVector.Marshal(b, m, deterministic)
}
func (m *M5GAuthenticationInformationAnswer_M5GAuthenticationVector) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M5GAuthenticationInformationAnswer_M5GAuthenticationVector.Merge(m, src)
}
func (m *M5GAuthenticationInformationAnswer_M5GAuthenticationVector) XXX_Size() int {
	return xxx_messageInfo_M5GAuthenticationInformationAnswer_M5GAuthenticationVector.Size(m)
}
func (m *M5GAuthenticationInformationAnswer_M5GAuthenticationVector) XXX_DiscardUnknown() {
	xxx_messageInfo_M5GAuthenticationInformationAnswer_M5GAuthenticationVector.DiscardUnknown(m)
}

var xxx_messageInfo_M5GAuthenticationInformationAnswer_M5GAuthenticationVector proto.InternalMessageInfo

func (m *M5GAuthenticationInformationAnswer_M5GAuthenticationVector) GetRand() []byte {
	if m != nil {
		return m.Rand
	}
	return nil
}

func (m *M5GAuthenticationInformationAnswer_M5GAuthenticationVector) GetXresStar() []byte {
	if m != nil {
		return m.XresStar
	}
	return nil
}

func (m *M5GAuthenticationInformationAnswer_M5GAuthenticationVector) GetAutn() []byte {
	if m != nil {
		return m.Autn
	}
	return nil
}

func (m *M5GAuthenticationInformationAnswer_M5GAuthenticationVector) GetKseaf() []byte {
	if m != nil {
		return m.Kseaf
	}
	return nil
}

func init() {
	proto.RegisterEnum("magma.lte.M5GErrorCode", M5GErrorCode_name, M5GErrorCode_value)
	proto.RegisterType((*M5GAuthenticationInformationRequest)(nil), "magma.lte.M5GAuthenticationInformationRequest")
	proto.RegisterType((*M5GAuthenticationInformationAnswer)(nil), "magma.lte.M5GAuthenticationInformationAnswer")
	proto.RegisterType((*M5GAuthenticationInformationAnswer_M5GAuthenticationVector)(nil), "magma.lte.M5GAuthenticationInformationAnswer.M5GAuthenticationVector")
}

func init() { proto.RegisterFile("lte/protos/subscriberauth.proto", fileDescriptor_6a742c81ad67f98d) }

var fileDescriptor_6a742c81ad67f98d = []byte{
	// 938 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xdd, 0x72, 0xdb, 0x44,
	0x14, 0xae, 0x93, 0xb4, 0x49, 0x36, 0x4e, 0xa3, 0x2e, 0xa1, 0x32, 0xf9, 0x19, 0xbb, 0x81, 0x99,
	0x78, 0x32, 0x83, 0xc3, 0x84, 0x31, 0xd7, 0xc8, 0xd2, 0xd6, 0x59, 0x2a, 0xad, 0xc4, 0x4a, 0x72,
	0x87, 0xde, 0xec, 0x28, 0xf6, 0xc6, 0xf5, 0xd4, 0x92, 0xc2, 0x4a, 0x4a, 0xe1, 0x8a, 0x6b, 0x7e,
	0x9e, 0x81, 0x19, 0xe0, 0x96, 0x9f, 0x6b, 0xfe, 0x0a, 0xf4, 0x0d, 0x60, 0x86, 0x87, 0xe0, 0x92,
	0x37, 0x60, 0x76, 0x65, 0x1b, 0x3b, 0x0c, 0x85, 0xde, 0xd8, 0xeb, 0x73, 0xbe, 0x73, 0xbe, 0xcf,
	0xdf, 0x39, 0x2b, 0x81, 0xfa, 0x38, 0xe7, 0xc7, 0x17, 0x22, 0xcd, 0xd3, 0xec, 0x38, 0x2b, 0xce,
	0xb2, 0xbe, 0x18, 0x9d, 0x71, 0x11, 0x15, 0xf9, 0xc3, 0x96, 0x8a, 0xc2, 0xf5, 0x38, 0x1a, 0xc6,
	0x51, 0x6b, 0x9c, 0xf3, 0x83, 0x27, 0xcb, 0xe0, 0x65, 0xa7, 0xdd, 0x35, 0x8a, 0xfc, 0x21, 0x4f,
	0xf2, 0x51, 0x3f, 0xca, 0x47, 0x69, 0x82, 0x93, 0xf3, 0x54, 0xc4, 0xea, 0x48, 0xf9, 0xbb, 0x05,
	0xcf, 0x72, 0xb8, 0x0b, 0xd6, 0x8b, 0x8c, 0x0b, 0x96, 0x44, 0x31, 0xaf, 0x55, 0x1a, 0x95, 0xe6,
	0x3a, 0x5d, 0x93, 0x01, 0x12, 0xc5, 0x1c, 0xde, 0x01, 0xd5, 0xcb, 0x51, 0x36, 0xca, 0xf9, 0x80,
	0x5d, 0x8c, 0xe3, 0xa4, 0xb6, 0xd4, 0xa8, 0x34, 0xab, 0x74, 0x63, 0x12, 0xf3, 0xc6, 0x71, 0x02,
	0x0d, 0xb0, 0x9f, 0x14, 0x31, 0x13, 0x65, 0x3b, 0x3e, 0x60, 0x71, 0x7b, 0x28, 0x15, 0xb1, 0x4b,
	0xde, 0xcf, 0x53, 0x91, 0xd5, 0x96, 0x1b, 0x95, 0xe6, 0x26, 0xdd, 0x49, 0x8a, 0x98, 0x4e, 0x31,
	0x4e, 0x09, 0xe9, 0x95, 0x08, 0xf8, 0x26, 0xd8, 0x1b, 0xc5, 0x31, 0x1f, 0x8c, 0xa2, 0x9c, 0x33,
	0xc1, 0xb3, 0x8b, 0x34, 0xc9, 0x38, 0xbb, 0x10, 0xfc, 0x9c, 0x0b, 0xc1, 0x07, 0xb5, 0x95, 0x46,
	0xa5, 0xb9, 0x46, 0x77, 0x66, 0x18, 0x3a, 0x81, 0x78, 0x53, 0x04, 0xac, 0x83, 0x0d, 0xc1, 0xb3,
	0xf7, 0x93, 0x3e, 0x1b, 0x25, 0xe7, 0x69, 0xed, 0xba, 0x92, 0x09, 0xca, 0x90, 0xfc, 0xcf, 0xf0,
	0x14, 0xdc, 0x59, 0x54, 0x59, 0xe4, 0x22, 0x4a, 0xd8, 0x90, 0xcb, 0xcf, 0xa9, 0xd2, 0x1b, 0x4a,
	0xe9, 0xfe, 0xbc, 0xd2, 0x50, 0xc2, 0xba, 0x12, 0x35, 0x15, 0xdb, 0x06, 0xfa, 0x7c, 0xed, 0x3c,
	0xed, 0xaa, 0xa2, 0xdd, 0x2e, 0x66, 0x35, 0xf4, 0x6f, 0x01, 0xaf, 0x81, 0xed, 0x8c, 0x8b, 0xcb,
	0x51, 0x32, 0x64, 0x09, 0xcf, 0x1f, 0xa7, 0xe2, 0x51, 0xe9, 0xf8, 0x9a, 0x72, 0x1c, 0x4e, 0x72,
	0xa4, 0x4c, 0x49, 0xef, 0x0f, 0x9e, 0x2e, 0x81, 0x83, 0x67, 0x0d, 0xd0, 0x48, 0xb2, 0xc7, 0x5c,
	0xc0, 0x37, 0x00, 0xe0, 0x42, 0xa4, 0x82, 0xf5, 0xd3, 0x41, 0x39, 0xc0, 0x9b, 0x27, 0x7a, 0x6b,
	0xb6, 0x07, 0x2d, 0xa7, 0xdd, 0x45, 0x32, 0x6f, 0xa6, 0x03, 0x4e, 0xd7, 0xf9, 0xf4, 0x08, 0x13,
	0xb0, 0x75, 0x75, 0x52, 0x4b, 0x8d, 0xe5, 0xe6, 0xc6, 0x09, 0x5a, 0x2c, 0xfe, 0x0f, 0xfe, 0x7f,
	0x42, 0x4a, 0xa3, 0xe8, 0xcd, 0x78, 0x61, 0xc8, 0x3b, 0x39, 0xd0, 0xff, 0x05, 0x0a, 0x21, 0x58,
	0x11, 0x51, 0x32, 0x50, 0xe2, 0xab, 0x54, 0x9d, 0xe5, 0x5a, 0xbe, 0x27, 0x78, 0xc6, 0xb2, 0x3c,
	0x12, 0x93, 0xb5, 0x5b, 0x93, 0x01, 0x3f, 0x8f, 0x54, 0x41, 0x54, 0xe4, 0x89, 0x5a, 0xad, 0x2a,
	0x55, 0x67, 0xb8, 0x0d, 0xae, 0x3f, 0xca, 0x78, 0x74, 0xae, 0xb6, 0xa5, 0x4a, 0xcb, 0x1f, 0x47,
	0x7f, 0xae, 0x80, 0xea, 0xbc, 0x03, 0x70, 0x13, 0xac, 0x87, 0xc4, 0x42, 0x77, 0x31, 0x41, 0x96,
	0x76, 0x0d, 0xbe, 0x08, 0x34, 0x27, 0xb4, 0x03, 0xcc, 0xa8, 0x1b, 0x12, 0x8b, 0x19, 0x61, 0x70,
	0xaa, 0xfd, 0xb1, 0x0a, 0xab, 0x60, 0xd5, 0x0f, 0x4d, 0x13, 0xf9, 0xbe, 0xf6, 0xeb, 0x16, 0xdc,
	0x06, 0x5b, 0x36, 0x76, 0x70, 0x80, 0x2c, 0x36, 0x8d, 0xfe, 0xb6, 0x05, 0x75, 0x00, 0x4d, 0xd7,
	0x71, 0x0c, 0x62, 0xb1, 0x90, 0xf8, 0xa1, 0xe7, 0xd2, 0x00, 0x59, 0xda, 0xb7, 0x3a, 0xbc, 0x0d,
	0x6e, 0x85, 0xc4, 0xe8, 0xd8, 0x88, 0x05, 0x2e, 0xb3, 0x90, 0x8d, 0x7b, 0x88, 0x6a, 0xdf, 0xe9,
	0x92, 0x8b, 0x22, 0xc3, 0x76, 0x18, 0x71, 0x03, 0xe6, 0x23, 0xda, 0x43, 0x96, 0xf6, 0xbd, 0x0e,
	0x37, 0xc1, 0x5a, 0xe0, 0xba, 0xac, 0x13, 0xfa, 0xef, 0x68, 0x3f, 0xe8, 0x10, 0x82, 0x4d, 0xdb,
	0x75, 0x3d, 0x66, 0xa1, 0x00, 0x99, 0xb2, 0xe3, 0x8f, 0x3a, 0xac, 0x81, 0x17, 0x28, 0xb2, 0x30,
	0x45, 0x66, 0xc0, 0x30, 0xb1, 0xb0, 0x69, 0x04, 0xd8, 0x25, 0xda, 0x13, 0x1d, 0xee, 0x01, 0xdd,
	0xf0, 0x3c, 0x7b, 0x12, 0x29, 0x85, 0x4c, 0x94, 0xfc, 0xa4, 0x18, 0x31, 0xe9, 0x19, 0x36, 0xb6,
	0x4e, 0x99, 0x45, 0x59, 0x07, 0x07, 0xbe, 0xf6, 0xf3, 0x7c, 0x98, 0x19, 0x3d, 0xaf, 0x0c, 0xff,
	0xa2, 0xc3, 0x5b, 0xa0, 0x1a, 0x92, 0x7b, 0xc4, 0xbd, 0x4f, 0x98, 0x87, 0x10, 0xd5, 0x9e, 0x96,
	0xed, 0xc3, 0xe0, 0x14, 0x91, 0x60, 0xca, 0x40, 0xd1, 0x5b, 0xa5, 0xac, 0xcf, 0xea, 0xb2, 0xc0,
	0x0d, 0x03, 0xe6, 0xde, 0x65, 0xbe, 0x67, 0x98, 0x48, 0xfb, 0xbc, 0x2e, 0xd5, 0x23, 0x1b, 0x99,
	0x0a, 0x6a, 0xbb, 0x7e, 0xa0, 0x7d, 0x51, 0x87, 0xbb, 0xe0, 0xb6, 0x6c, 0xe2, 0x52, 0xfc, 0xe0,
	0x4a, 0x8f, 0x8f, 0x0f, 0x15, 0xa9, 0x8f, 0x28, 0x9b, 0x30, 0x6b, 0x1f, 0x1e, 0x4a, 0x63, 0xa7,
	0x3a, 0x7c, 0xe4, 0xfb, 0xb2, 0x02, 0x5b, 0xda, 0x47, 0x87, 0x70, 0x1f, 0xd4, 0xa6, 0x09, 0xe4,
	0xf9, 0xcc, 0x0f, 0x3b, 0xbe, 0x49, 0xb1, 0xa7, 0xbc, 0xf8, 0xf2, 0x48, 0x8e, 0x89, 0x1a, 0x81,
	0x72, 0xd7, 0xb0, 0x6d, 0xf7, 0x3e, 0xb2, 0xb4, 0xaf, 0x8e, 0x94, 0x77, 0xae, 0xe1, 0x60, 0xd2,
	0x5d, 0xc8, 0x7c, 0x72, 0x28, 0xe7, 0x84, 0xde, 0x0e, 0xb1, 0xe7, 0x20, 0x12, 0xcc, 0xf8, 0xbf,
	0x56, 0x15, 0x21, 0xb9, 0x57, 0xd2, 0xd3, 0x5e, 0x59, 0x68, 0x21, 0xed, 0x9b, 0x23, 0xf8, 0x0a,
	0xa8, 0x5f, 0xb1, 0xc3, 0x32, 0x02, 0x83, 0x85, 0xc4, 0xe8, 0x19, 0xd8, 0x96, 0x23, 0xd7, 0x7e,
	0x6f, 0x9c, 0x7c, 0x5a, 0x01, 0xbb, 0x4e, 0xbb, 0xeb, 0xcf, 0x1e, 0xd0, 0x8b, 0x4b, 0x0f, 0x3f,
	0x00, 0x7b, 0xcf, 0xba, 0x57, 0xb0, 0xf5, 0x3f, 0x2f, 0xe0, 0xe4, 0x21, 0xb5, 0xf3, 0xea, 0x73,
	0x5d, 0xd8, 0x83, 0x6b, 0x9d, 0xdd, 0x07, 0x2f, 0xa9, 0x8a, 0x63, 0xf9, 0x3a, 0xe9, 0x8f, 0xd3,
	0x62, 0x70, 0x3c, 0x4c, 0x27, 0xef, 0x95, 0xb3, 0x1b, 0xea, 0xfb, 0xf5, 0xbf, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xac, 0xb0, 0xc2, 0x2a, 0x6c, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// M5GSubscriberAuthenticationClient is the client API for M5GSubscriberAuthentication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type M5GSubscriberAuthenticationClient interface {
	// Authentication-Information (Code 318)
	M5GAuthenticationInformation(ctx context.Context, in *M5GAuthenticationInformationRequest, opts ...grpc.CallOption) (*M5GAuthenticationInformationAnswer, error)
}

type m5GSubscriberAuthenticationClient struct {
	cc grpc.ClientConnInterface
}

func NewM5GSubscriberAuthenticationClient(cc grpc.ClientConnInterface) M5GSubscriberAuthenticationClient {
	return &m5GSubscriberAuthenticationClient{cc}
}

func (c *m5GSubscriberAuthenticationClient) M5GAuthenticationInformation(ctx context.Context, in *M5GAuthenticationInformationRequest, opts ...grpc.CallOption) (*M5GAuthenticationInformationAnswer, error) {
	out := new(M5GAuthenticationInformationAnswer)
	err := c.cc.Invoke(ctx, "/magma.lte.M5GSubscriberAuthentication/M5GAuthenticationInformation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// M5GSubscriberAuthenticationServer is the server API for M5GSubscriberAuthentication service.
type M5GSubscriberAuthenticationServer interface {
	// Authentication-Information (Code 318)
	M5GAuthenticationInformation(context.Context, *M5GAuthenticationInformationRequest) (*M5GAuthenticationInformationAnswer, error)
}

// UnimplementedM5GSubscriberAuthenticationServer can be embedded to have forward compatible implementations.
type UnimplementedM5GSubscriberAuthenticationServer struct {
}

func (*UnimplementedM5GSubscriberAuthenticationServer) M5GAuthenticationInformation(ctx context.Context, req *M5GAuthenticationInformationRequest) (*M5GAuthenticationInformationAnswer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method M5GAuthenticationInformation not implemented")
}

func RegisterM5GSubscriberAuthenticationServer(s *grpc.Server, srv M5GSubscriberAuthenticationServer) {
	s.RegisterService(&_M5GSubscriberAuthentication_serviceDesc, srv)
}

func _M5GSubscriberAuthentication_M5GAuthenticationInformation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(M5GAuthenticationInformationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(M5GSubscriberAuthenticationServer).M5GAuthenticationInformation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/magma.lte.M5GSubscriberAuthentication/M5GAuthenticationInformation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(M5GSubscriberAuthenticationServer).M5GAuthenticationInformation(ctx, req.(*M5GAuthenticationInformationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _M5GSubscriberAuthentication_serviceDesc = grpc.ServiceDesc{
	ServiceName: "magma.lte.M5GSubscriberAuthentication",
	HandlerType: (*M5GSubscriberAuthenticationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "M5GAuthenticationInformation",
			Handler:    _M5GSubscriberAuthentication_M5GAuthenticationInformation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lte/protos/subscriberauth.proto",
}
