---
#------------------
#Cluster-specific Variables
#Use them to customize each deployment
#------------------
#Orc8r deployment variables
orc8rClusterName: Sydney
orc8rDomainName: bbbath.fbmagma.ninja
orc8rLabel: 1.5.0
orc8rVersion: v1.5
gitHelmRepo: helm15


#AWS variables
awsBootKey: "{{ keyBoot }}"
awsHostKey: "{{ keyHost }}"
awsAgwRegion: ap-northeast-1
awsOrc8rRegion: ap-southeast-2
awsAgwAz: ap-northeast-1a
awsAgwVersion: v1.5

awsAgwAmi: ami-09265db477af05f54
awsCloudstrapperAmi: ami-03865ac2b925f8056

#------------------
#Cluster-specific Presets
#------------------

#AWS Resource Names
orc8rTfSecrets: orc8r-secrets
orc8rTfVpc: orc8r
orc8rTfCluster: orc8r
orc8rTfEs: orc8r-es

#------------------
#Cluster-specific Variables ends
#------------------
