---
#
# Copyright (c) 2017-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

version: 0.0
os: linux
files:
  - source: ansible
    destination: /var/opt/magma/ansible
  - source: bin
    destination: /var/opt/magma/bin
  - source: plugins
    destination: /var/opt/magma/plugins
  - source: configs
    destination: /etc/magma
hooks:
  BeforeInstall:
    - location: scripts/prepare_server
      timeout: 300
      runas: root
    - location: scripts/set_proxy_services
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/run_ansible
      timeout: 300
      runas: root
