---
# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.
- name: Read in a list of modules if magma_modules is not defined
  command: ls /etc/magma/configs/
  register: module_names

- name: Read in service_registry
  slurp:
    src: '/etc/magma/configs/{{ item | basename }}/service_registry.yml'
  loop: "{{ module_names['stdout_lines']  }}"
  register: service_registry_slurp

- name: Load service_registry into a variable
  vars:
    registry: "{{ item['content'] | b64decode | from_yaml }}"
    services: "{{ registry.services if registry.services is defined else {} }}"
    combined: "{{ service_registry | default({}) | combine(services) }}"
  set_fact:
    service_registry: '{{ combined }}'
  loop: "{{ service_registry_slurp.results }}"