// Code generated by go-swagger; DO NOT EDIT.

package wifi_networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"magma/orc8r/cloud/go/obsidian/swagger/v1/models"
)

// NewPutWifiNetworkIDDescriptionParams creates a new PutWifiNetworkIDDescriptionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutWifiNetworkIDDescriptionParams() *PutWifiNetworkIDDescriptionParams {
	return &PutWifiNetworkIDDescriptionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutWifiNetworkIDDescriptionParamsWithTimeout creates a new PutWifiNetworkIDDescriptionParams object
// with the ability to set a timeout on a request.
func NewPutWifiNetworkIDDescriptionParamsWithTimeout(timeout time.Duration) *PutWifiNetworkIDDescriptionParams {
	return &PutWifiNetworkIDDescriptionParams{
		timeout: timeout,
	}
}

// NewPutWifiNetworkIDDescriptionParamsWithContext creates a new PutWifiNetworkIDDescriptionParams object
// with the ability to set a context for a request.
func NewPutWifiNetworkIDDescriptionParamsWithContext(ctx context.Context) *PutWifiNetworkIDDescriptionParams {
	return &PutWifiNetworkIDDescriptionParams{
		Context: ctx,
	}
}

// NewPutWifiNetworkIDDescriptionParamsWithHTTPClient creates a new PutWifiNetworkIDDescriptionParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutWifiNetworkIDDescriptionParamsWithHTTPClient(client *http.Client) *PutWifiNetworkIDDescriptionParams {
	return &PutWifiNetworkIDDescriptionParams{
		HTTPClient: client,
	}
}

/* PutWifiNetworkIDDescriptionParams contains all the parameters to send to the API endpoint
   for the put wifi network ID description operation.

   Typically these are written to a http.Request.
*/
type PutWifiNetworkIDDescriptionParams struct {

	/* Description.

	   New name for the network
	*/
	Description models.NetworkDescription

	/* NetworkID.

	   Network ID
	*/
	NetworkID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put wifi network ID description params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutWifiNetworkIDDescriptionParams) WithDefaults() *PutWifiNetworkIDDescriptionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put wifi network ID description params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutWifiNetworkIDDescriptionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put wifi network ID description params
func (o *PutWifiNetworkIDDescriptionParams) WithTimeout(timeout time.Duration) *PutWifiNetworkIDDescriptionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put wifi network ID description params
func (o *PutWifiNetworkIDDescriptionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put wifi network ID description params
func (o *PutWifiNetworkIDDescriptionParams) WithContext(ctx context.Context) *PutWifiNetworkIDDescriptionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put wifi network ID description params
func (o *PutWifiNetworkIDDescriptionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put wifi network ID description params
func (o *PutWifiNetworkIDDescriptionParams) WithHTTPClient(client *http.Client) *PutWifiNetworkIDDescriptionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put wifi network ID description params
func (o *PutWifiNetworkIDDescriptionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDescription adds the description to the put wifi network ID description params
func (o *PutWifiNetworkIDDescriptionParams) WithDescription(description models.NetworkDescription) *PutWifiNetworkIDDescriptionParams {
	o.SetDescription(description)
	return o
}

// SetDescription adds the description to the put wifi network ID description params
func (o *PutWifiNetworkIDDescriptionParams) SetDescription(description models.NetworkDescription) {
	o.Description = description
}

// WithNetworkID adds the networkID to the put wifi network ID description params
func (o *PutWifiNetworkIDDescriptionParams) WithNetworkID(networkID string) *PutWifiNetworkIDDescriptionParams {
	o.SetNetworkID(networkID)
	return o
}

// SetNetworkID adds the networkId to the put wifi network ID description params
func (o *PutWifiNetworkIDDescriptionParams) SetNetworkID(networkID string) {
	o.NetworkID = networkID
}

// WriteToRequest writes these params to a swagger request
func (o *PutWifiNetworkIDDescriptionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Description); err != nil {
		return err
	}

	// path param network_id
	if err := r.SetPathParam("network_id", o.NetworkID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
