// Code generated by go-swagger; DO NOT EDIT.

package wifi_networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"magma/orc8r/cloud/go/obsidian/swagger/v1/models"
)

// PutWifiNetworkIDWifiReader is a Reader for the PutWifiNetworkIDWifi structure.
type PutWifiNetworkIDWifiReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutWifiNetworkIDWifiReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewPutWifiNetworkIDWifiNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPutWifiNetworkIDWifiDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPutWifiNetworkIDWifiNoContent creates a PutWifiNetworkIDWifiNoContent with default headers values
func NewPutWifiNetworkIDWifiNoContent() *PutWifiNetworkIDWifiNoContent {
	return &PutWifiNetworkIDWifiNoContent{}
}

/* PutWifiNetworkIDWifiNoContent describes a response with status code 204, with default header values.

Success
*/
type PutWifiNetworkIDWifiNoContent struct {
}

func (o *PutWifiNetworkIDWifiNoContent) Error() string {
	return fmt.Sprintf("[PUT /wifi/{network_id}/wifi][%d] putWifiNetworkIdWifiNoContent ", 204)
}

func (o *PutWifiNetworkIDWifiNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutWifiNetworkIDWifiDefault creates a PutWifiNetworkIDWifiDefault with default headers values
func NewPutWifiNetworkIDWifiDefault(code int) *PutWifiNetworkIDWifiDefault {
	return &PutWifiNetworkIDWifiDefault{
		_statusCode: code,
	}
}

/* PutWifiNetworkIDWifiDefault describes a response with status code -1, with default header values.

Unexpected Error
*/
type PutWifiNetworkIDWifiDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the put wifi network ID wifi default response
func (o *PutWifiNetworkIDWifiDefault) Code() int {
	return o._statusCode
}

func (o *PutWifiNetworkIDWifiDefault) Error() string {
	return fmt.Sprintf("[PUT /wifi/{network_id}/wifi][%d] PutWifiNetworkIDWifi default  %+v", o._statusCode, o.Payload)
}
func (o *PutWifiNetworkIDWifiDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *PutWifiNetworkIDWifiDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
