// Code generated by go-swagger; DO NOT EDIT.

package wifi_networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"magma/orc8r/cloud/go/obsidian/swagger/v1/models"
)

// NewPutWifiNetworkIDParams creates a new PutWifiNetworkIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutWifiNetworkIDParams() *PutWifiNetworkIDParams {
	return &PutWifiNetworkIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutWifiNetworkIDParamsWithTimeout creates a new PutWifiNetworkIDParams object
// with the ability to set a timeout on a request.
func NewPutWifiNetworkIDParamsWithTimeout(timeout time.Duration) *PutWifiNetworkIDParams {
	return &PutWifiNetworkIDParams{
		timeout: timeout,
	}
}

// NewPutWifiNetworkIDParamsWithContext creates a new PutWifiNetworkIDParams object
// with the ability to set a context for a request.
func NewPutWifiNetworkIDParamsWithContext(ctx context.Context) *PutWifiNetworkIDParams {
	return &PutWifiNetworkIDParams{
		Context: ctx,
	}
}

// NewPutWifiNetworkIDParamsWithHTTPClient creates a new PutWifiNetworkIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutWifiNetworkIDParamsWithHTTPClient(client *http.Client) *PutWifiNetworkIDParams {
	return &PutWifiNetworkIDParams{
		HTTPClient: client,
	}
}

/* PutWifiNetworkIDParams contains all the parameters to send to the API endpoint
   for the put wifi network ID operation.

   Typically these are written to a http.Request.
*/
type PutWifiNetworkIDParams struct {

	/* NetworkID.

	   Network ID
	*/
	NetworkID string

	/* WifiNetwork.

	   Full desired configuration of the network
	*/
	WifiNetwork *models.WifiNetwork

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put wifi network ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutWifiNetworkIDParams) WithDefaults() *PutWifiNetworkIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put wifi network ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutWifiNetworkIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put wifi network ID params
func (o *PutWifiNetworkIDParams) WithTimeout(timeout time.Duration) *PutWifiNetworkIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put wifi network ID params
func (o *PutWifiNetworkIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put wifi network ID params
func (o *PutWifiNetworkIDParams) WithContext(ctx context.Context) *PutWifiNetworkIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put wifi network ID params
func (o *PutWifiNetworkIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put wifi network ID params
func (o *PutWifiNetworkIDParams) WithHTTPClient(client *http.Client) *PutWifiNetworkIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put wifi network ID params
func (o *PutWifiNetworkIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNetworkID adds the networkID to the put wifi network ID params
func (o *PutWifiNetworkIDParams) WithNetworkID(networkID string) *PutWifiNetworkIDParams {
	o.SetNetworkID(networkID)
	return o
}

// SetNetworkID adds the networkId to the put wifi network ID params
func (o *PutWifiNetworkIDParams) SetNetworkID(networkID string) {
	o.NetworkID = networkID
}

// WithWifiNetwork adds the wifiNetwork to the put wifi network ID params
func (o *PutWifiNetworkIDParams) WithWifiNetwork(wifiNetwork *models.WifiNetwork) *PutWifiNetworkIDParams {
	o.SetWifiNetwork(wifiNetwork)
	return o
}

// SetWifiNetwork adds the wifiNetwork to the put wifi network ID params
func (o *PutWifiNetworkIDParams) SetWifiNetwork(wifiNetwork *models.WifiNetwork) {
	o.WifiNetwork = wifiNetwork
}

// WriteToRequest writes these params to a swagger request
func (o *PutWifiNetworkIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param network_id
	if err := r.SetPathParam("network_id", o.NetworkID); err != nil {
		return err
	}
	if o.WifiNetwork != nil {
		if err := r.SetBodyParam(o.WifiNetwork); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
