# Copyright (c) 2018-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

release_group: null

magmalte:
  manifests:
    secrets: true
    deployment: true
    service: true

  env:
    api_host: orc8r-proxy.magma.svc.cluster.local:9443
    host: 0.0.0.0
    port: 8081
    mapbox_access_token: ""
    mysql_host: mariadb.magma.svc.cluster.local
    mysql_db: magma
    mysql_user: magma
    mysql_pass: password

  labels:
    node_selector_key: nodetype
    node_selector_value: magma

  image:
    repository: <registry>/magmalte
    tag: latest
    pullPolicy: Always

  service:
    type: ClusterIP
    http:
      port: 8081
      targetport: 8081
      nodePort: ""


## Nginx-Proxy
#
nginx:
  manifests:
    configmap: true
    secrets: true
    deployment: true
    service: true

  labels:
    node_selector_key: nodetype
    node_selector_value: magma

  image:
    repository: nginx
    tag: latest
    pullPolicy: Always

  service:
    type: ClusterIP
    https:
      port: 443
      targetport: 443
      nodePort: ""

## POD Resource 

pod:
  replicas:
    nginx:
      server: 1
    magmalte:
      server: 1
  affinity:
    anti:
      type:
        default: preferredDuringSchedulingIgnoredDuringExecution
      topologyKey:
        default: kubernetes.io/hostname
  resources:
    enabled: False
    nginx:
      requests:
        memory: "512Mi"
        cpu: "100m"
      limits:
        memory: "1024Mi"
        cpu: "2000m"
    magmalte:
      requests:
        memory: "1024Mi"
        cpu: "100m"
      limits:
        memory: "2048Mi"
        cpu: "2000m"
