---
swagger: '2.0'

info:
  title: Magma
  description: Magma REST APIs
  version: 1.1.2

basePath: /magma

consumes:
  - application/json

produces:
  - application/json

schemes:
  - https
  - http

tags:
  - name: Networks
    description: Everything about networks
  - name: Gateways
    description: Provision and manage gateways
  - name: Operators
    description: Access Control Operations and Participants
  - name: TestController
    description: Controller for CI Test & Upgrade Services

paths:
  /foo:
    get:
      summary: Mock API path so the YAML passes spec
      responses:
        '200':
          description: Bar baz
          schema:
            type: integer

responses:
  # Common responses
  UnexpectedError:
    description: Unexpected Error
    schema:
      $ref: '#/definitions/error'

parameters:
  # Common parameters
  network_id:
    in: path
    name: network_id
    description: Network ID
    required: true
    type: string
  gateway_id:
    in: path
    name: gateway_id
    description: Gateway ID
    required: true
    type: string
  subscriber_id:
    in: path
    name: subscriber_id
    description: Subscriber ID
    required: true
    type: string
  device_id:
    in: path
    name: device_id
    description: Edge device ID
    required: true
    type: string
  enodeb_id:
    in: path
    name: enodeb_id
    description: Enodeb device Serial ID
    required: true
    type: string

definitions:
  # Common definitions
  device_id:
    type: string
    minLength: 1
    example: PDU
  network_id:
    type: string
    minLength: 1
    example: NFHDZAQU8Pyw2N91nbNdGjk5e
  gateway_id:
    type: string
    minLength: 1
    example: NFHDZAQU8Pyw2N91nbNdGjk5e.22ffea10-7fc4-4427-975a-b9e4ce8f6f4d
  subscriber_id:
    type: string
    pattern: '^(IMSI\d{10,15})$'
    example: IMSI208950000000010
  enodeb_id:
    type: string
    minLength: 1
    example: 120200002618AGP0003
  error:
    type: object
    required:
    - message
    properties:
      message:
        type: string
        example: Error string

