- name: Query secrets manager
  ansible.builtin.shell: aws secretsmanager get-secret-value --secret-id {{ infra_configs.secretsmanager_orc8r_secret | quote }} || /bin/true
  register: result
  tags: install_precheck

- name: Verify if secrets already present
  assert:
    that: '"ResourceNotFoundException" in result.stderr'
    fail_msg:
      - "secret {{ infra_configs.secretsmanager_orc8r_secret}} already present"
      - "Remove secrets 'aws secretsmanager delete-secret  --force-delete --secret-id {{ infra_configs.secretsmanager_orc8r_secret | quote }}'"
  tags: install_precheck

