- name: Query secrets manager to check if secretsID is already present
  ansible.builtin.shell: aws secretsmanager get-secret-value --secret-id {{ infra_configs.secretsmanager_orc8r_secret | quote }} || /bin/true
  register: result
  failed_when: '"ResourceNotFoundException" not in result.stderr'
  tags: install_precheck
