---
- name: check if gateway name is defined
  assert:
    that:
      - idGw is defined

- name: identify sgi subnet id using tag
  ec2_vpc_subnet_info:
    filters:
      "tag:Name": "{{ siteName }}-SgiSubnet"
  register: valSgiSubnet

- name: identify s1 subnet id using tag
  ec2_vpc_subnet_info:
    filters:
      "tag:Name": "{{ siteName }}-EnodebSubnet"
  register: valEnodebSubnet

- name: set sgi subnet fact
  set_fact:
    factSgiSubnetId: "{{ valSgiSubnet.subnets[0].subnet_id }}"

- name: set sgi subnet fact
  set_fact:
    factEnodebSubnetId: "{{ valEnodebSubnet.subnets[0].subnet_id }}"

- name: identify security group using tag, of the form sitename-secgroup
  ec2_group_info:
    filters:
      group-name: "{{ secGroup }}{{ siteName }}"
  register: valSecGroup

- name: set security group fact
  set_fact:
    factSecGroup: "{{ valSecGroup.security_groups[0].group_id }}"


- name: provision agw base with dual nics for deploy
  cloudformation:
    stack_name: "stack{{ siteName }}{{ idGw }}"
    state: present
    template: "roles/cfn/cfnMagmaAgwPublicDual.json"
    template_parameters:
      paramImageBase: "{{ awsAgwAmi }}"
      paramSubnetSgi: "{{ factSgiSubnetId }}"
      paramSubnetEnodeb: "{{ factEnodebSubnetId }}"
      paramAzHome: "{{ awsAgwAz }}"
      paramSecGroup: "{{ factSecGroup }}"
      paramSshKey: "{{ awsHostKey }}"
      paramAgwTagName: "{{ idGw }}"
      paramAgwTagSite: "{{ siteName }}"
      paramAgwInstanceType: "t2.medium"
  when: agwDevops is undefined

- name: provision agw base with dual nics for devops
  cloudformation:
    stack_name: "stack{{ siteName }}{{ idGw }}"
    state: present
    template: "roles/cfn/cfnMagmaAgwPublicDual.json"
    template_parameters:
      paramImageBase: "{{ buildUbuntuAmi }}"
      paramSubnetSgi: "{{ factSgiSubnetId }}"
      paramSubnetEnodeb: "{{ factEnodebSubnetId }}"
      paramAzHome: "{{ awsAgwAz }}"
      paramSecGroup: "{{ factSecGroup }}"
      paramSshKey: "{{ awsHostKey }}"
      paramAgwTagName: "{{ idGw }}"
      paramAgwTagSite: "{{ siteName }}"
      paramAgwInstanceType: "t2.medium"
  when: agwDevops is defined
