name: Reviewdog
on:  # yamllint disable-line rule:truthy
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - .github/workflows/cpplint.yml
      - lte/gateway/c/**
      - orc8r/gateway/c/**

##
#  Cpplint aims to lint to the Google Style guide. For detailed
#  rationale on each linting rule, see
#  https://google.github.io/styleguide/cppguide.html
##
#  To suppress false-positive errors of a certain category, add a
#  'NOLINT(category)' comment to the line.  NOLINT or NOLINT(*)
#  suppresses errors of all categories on that line.
##
#  For details on cpplint optinos see the detailed comments in
#  https://github.com/google/styleguide/blob/gh-pages/cpplint/cpplint.py
##

jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: reviewdog/action-cpplint@master
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
        flags: --linelength=120  # Optional
        # filter: "-readability/braces\
        #  ,-whitespace/braces\
        #  ,-whitespace/comments\
        #  ,-whitespace/indent\
        #  ,-whitespace/newline\
        #  ,-whitespace/operators\
        #  ,-whitespace/parens\
        #  "  # Optional