---
name: cwag-workflow

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
    paths:
      - 'orc8r/**'
      - 'lte/**'
      - 'feg/**'
      - 'cwf/**'
  pull_request:
    branches:
      - master
jobs:
  cwag-precommit:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on  # yamllint disable-line rule:truthy
      MAGMA_ROOT: "${{ github.workspace }}"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.7'
      - name: Run golang_before_install.sh script
        run: ./circleci/golang_before_install.sh
      - name: Run go mod download with retry
        uses: nick-invision/retry@v2
        with:
          command: cd ${MAGMA_ROOT}/cwf/gateway && go mod download
          timeout_minutes: 10
      - name: Run precommit
        run: |
            cd ${MAGMA_ROOT}/cwf/gateway
            make -C ${MAGMA_ROOT}/cwf/gateway precommit
            cd ${MAGMA_ROOT}/cwf/gateway
            make -C ${MAGMA_ROOT}/cwf/gateway/integ_tests precommit
      # Notify ci channel when failing
      # Plugin info: https://github.com/marketplace/actions/slack-notify
      - name: Notify failure to slack
        if: failure() && github.ref == 'refs/heads/master'
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_CI }}
          SLACK_TITLE: "Github action cwag-precommit update failed"
          SLACK_USERNAME: "Cwag workflow"
          SLACK_ICON_EMOJI: ":boom:"
          SLACK_COLOR: "#FF0000"
  cwag-build:
    runs-on: ubuntu-latest
    env:
      MAGMA_ROOT: "${{ github.workspace }}"
    steps:
      - uses: actions/checkout@v2
      - name: Run docker-compose
        uses: nick-invision/retry@v2
        with:
          command: cd ${MAGMA_ROOT}/cwf/gateway/docker && docker-compose build --parallel
          max_attempts: 2
          timeout_minutes: 10
          # TODO bring up the containers and check for crashloops
  xwfm-test:
    runs-on: ubuntu-latest
    env:
      MAGMA_ROOT: "${{ github.workspace }}"
    steps:
      - uses: actions/checkout@v2
      - name: Loading openvswitch kernel module
        run: sudo modprobe openvswitch
      - name: Run docker compose
        # yamllint disable rule:line-length
        run: |
              env
              docker login -u ${{ secrets.XWF_ARTIFACTORY_USER }} -p ${{ secrets.XWF_ARTIFACTORY_API_KEY }} ${{ secrets.XWF_ARTIFACTORY_LINK}}
              cd ${MAGMA_ROOT}/xwf/docker/
              docker-compose pull || true
              docker-compose build --parallel && docker-compose up -d && docker exec tests pytest --log-cli-level=info code/tests.py
      # Notify ci channel when failing
      # Plugin info: https://github.com/marketplace/actions/slack-notify
      # yamllint enable
      - name: Notify failure to slack
        if: failure() && github.ref == 'refs/heads/master'
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_CI }}
          SLACK_TITLE: "Github action xwfm-test failed"
          SLACK_USERNAME: "Cwag workflow"
          SLACK_ICON_EMOJI: ":boom:"
          SLACK_COLOR: "#FF0000"
      # Notify ci channel when push succeeds
      - name: Notify success to Slack
        if: success() && github.ref == 'refs/heads/master'
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL_ARTIFACTS }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_OSS }}
          SLACK_TITLE: "*xwfm-test test succeeded*"
          SLACK_USERNAME: "Cwag workflow"
          SLACK_ICON_EMOJI: ":heavy_check_mark:"
          SLACK_COLOR: "#FF0000"
  cwag-deploy:
    needs:
      - cwag-precommit
      # TODO Should also need cwf-integ-test
      # TODO Requires release hold
    runs-on: ubuntu-latest
    env:
      MAGMA_ROOT: "${{ github.workspace }}"
      DOCKER_REGISTRY: cwf_
    steps:
      - uses: actions/checkout@v2
      - name: Run docker compose
        # yamllint disable rule:line-length
        uses: nick-invision/retry@v2
        with:
          command: cd ${MAGMA_ROOT}/cwf/gateway/docker && docker-compose -f docker-compose.yml -f docker-compose.override.yml build --parallel
          max_attempts: 2
          timeout_minutes: 10
      - name: Tag and push to Docker Registry
        if: github.ref == 'refs/heads/master'
        env:
          DOCKER_REGISTRY: "${{ secrets.DOCKER_REGISTRY }}"
          DOCKER_USERNAME: "${{ secrets.DOCKER_USERNAME }}"
          DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
        run: |
            ./ci-scripts/tag-push-docker.sh --images 'cwag_go|gateway_go|gateway_python|gateway_sessiond|gateway_pipelined' --tag "${GITHUB_SHA:0:8}" --tag-latest true --project cwag
      - name: Tag and push to Jfrog Registry
        if: github.ref == 'refs/heads/master'
        env:
          DOCKER_REGISTRY: "${{ secrets.JFROG_DOCKER_ORC8R_REGISTRY }}"
          DOCKER_USERNAME: "${{ secrets.JFROG_USERNAME }}"
          DOCKER_PASSWORD: "${{ secrets.JFROG_PASSWORD }}"
        run: |
            ./ci-scripts/tag-push-docker.sh --images 'cwag_go|gateway_go|gateway_python|gateway_sessiond|gateway_pipelined' --tag "${GITHUB_SHA:0:8}" --tag-latest true --project cwag
      # Notify ci channel when failing
      # Plugin info: https://github.com/marketplace/actions/slack-notify
      # yamllint enable
      - name: Notify failure to slack
        if: failure() && github.ref == 'refs/heads/master'
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_CI }}
          SLACK_TITLE: "Github action cwag-deploy failed"
          SLACK_USERNAME: "Cwag workflow"
          SLACK_ICON_EMOJI: ":boom:"
          SLACK_COLOR: "#FF0000"
      # Notify ci channel when push succeeds
      - name: Notify success to slack
        if: success() && github.ref == 'refs/heads/master'
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL_ARTIFACTS }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_OSS }}
          SLACK_TITLE: "*Cwag Artifact Has Been Published*"
          SLACK_USERNAME: "Cwag workflow"
          SLACK_ICON_EMOJI: ":heavy_check_mark:"
          SLACK_COLOR: "#00FF00"
  xwfm-deploy-latest:
    needs:
      - cwag-deploy
      - xwfm-test
    runs-on: ubuntu-latest
    env:
      MAGMA_ROOT: "${{ github.workspace }}"
      DOCKER_REGISTRY: "${{ secrets.DOCKER_REGISTRY }}"
      DOCKER_USERNAME: "${{ secrets.DOCKER_USERNAME }}"
      DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
    steps:
      - uses: actions/checkout@v2
      - name: Build xwf go radius
        run: |
              cd ${MAGMA_ROOT}/feg
              docker build --build-arg BUILD_NUM=${CIRCLE_SHA1:0:8} --tag goradius -f radius/src/Dockerfile ./
      - name: Tag and push to Docker Registry
        if: github.ref == 'refs/heads/master'
        # yamllint disable rule:line-length
        run: |
            ./ci-scripts/tag-push-docker.sh --images 'goradius' --tag '${GITHUB_SHA:0:8}' --tag-latest true --project cwag
      - name: Load openvswitch kernel module for xwf integ test
        # yamllint enable
        run: sudo modprobe openvswitch
      - name: Build xwfm-integ-tests
        run: |
              cd ${MAGMA_ROOT}
              docker build --tag xwfm-integ-tests -f xwf/gateway/integ_tests/gw/Dockerfile ./
      - name: Tag and push to Docker Registry
        if: github.ref == 'refs/heads/master'
        # yamllint disable rule:line-length
        run: |
            ./ci-scripts/tag-push-docker.sh --images 'xwfm-integ-tests' --tag "${GITHUB_SHA:0:8}" --tag-latest true --project cwag
      # Notify ci channel when failing
      # Plugin info: https://github.com/marketplace/actions/slack-notify
      # yamllint enable
      - name: Notify failure to slack
        if: failure() && github.ref == 'refs/heads/master'
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_CI }}
          SLACK_TITLE: "Github action xwfm-deploy-latest failed"
          SLACK_USERNAME: "Cwag workflow"
          SLACK_ICON_EMOJI: ":boom:"
          SLACK_COLOR: "#FF0000"
      # Notify ci channel when push succeeds
      - name: Notify success to slack
        if: success() && github.ref == 'refs/heads/master'
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL_ARTIFACTS }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_OSS }}
          SLACK_TITLE: "*xwfm Artifact Has Been Published*"
          SLACK_USERNAME: "Cwag workflow"
          SLACK_ICON_EMOJI: ":heavy_check_mark:"
          SLACK_COLOR: "#00FF00"
  cwag-deploy-latest:
    needs:
      - cwag-deploy
      - xwfm-deploy-latest
      # TODO Should also need cwf-integ-test
      # TODO Requires release hold
    runs-on: ubuntu-latest
    env:
      MAGMA_ROOT: "${{ github.workspace }}"
      DOCKER_REGISTRY: cwf_
    steps:
      - uses: actions/checkout@v2
      - name: Run docker compose
        # yamllint disable rule:line-length
        uses: nick-invision/retry@v2
        with:
          command: cd ${MAGMA_ROOT}/cwf/gateway/docker && docker-compose -f docker-compose.yml -f docker-compose.override.yml build --parallel
          max_attempts: 2
      - name: Tag and push to Docker Registry
        if: github.ref == 'refs/heads/master'
        env:
          DOCKER_REGISTRY: "${{ secrets.DOCKER_REGISTRY }}"
          DOCKER_USERNAME: "${{ secrets.DOCKER_USERNAME }}"
          DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
        run: |
            ./ci-scripts/tag-push-docker.sh --images 'gateway_python|gateway_pipelined|gateway_go' --tag "${GITHUB_SHA:0:8}" --tag-latest true --project cwag
      - name: Tag and push to Jfrog Registry
        if: github.ref == 'refs/heads/master'
        env:
          DOCKER_REGISTRY: "${{ secrets.JFROG_DOCKER_ORC8R_REGISTRY }}"
          DOCKER_USERNAME: "${{ secrets.JFROG_USERNAME }}"
          DOCKER_PASSWORD: "${{ secrets.JFROG_PASSWORD }}"
        run: |
            ./ci-scripts/tag-push-docker.sh --images 'gateway_python|gateway_pipelined|gateway_go' --tag "${GITHUB_SHA:0:8}" --tag-latest true --project cwag
      # Notify ci channel when failing
      # Plugin info: https://github.com/marketplace/actions/slack-notify
      # yamllint enable
      - name: Notify failure to slack
        if: failure() && github.ref == 'refs/heads/master'
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_CI }}
          SLACK_TITLE: "Github action cwag-deploy failed"
          SLACK_USERNAME: "Cwag workflow"
          SLACK_ICON_EMOJI: ":boom:"
          SLACK_COLOR: "#FF0000"
      # Notify ci channel when push succeeds
      - name: Notify success to slack
        if: success() && github.ref == 'refs/heads/master'
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL_ARTIFACTS }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_OSS }}
          SLACK_TITLE: "*Cwag Artifact Has Been Published*"
          SLACK_USERNAME: "Cwag workflow"
          SLACK_ICON_EMOJI: ":heavy_check_mark:"
          SLACK_COLOR: "#00FF00"
